### ISSUE TITLE
Should there be an easy batch?

### ISSUE THREAD

**Issue by Oregon-Tech-Ninja** [asdine/storm#1]
If I'm not mistaken, don't you have to call ".Batch" instead of ".Update" if you want to batch calls together? This would be pretty easy to implement, but I'm unsure if it is necessary (Do update calls already get batched together?)

Just wondering, I like this code though, I was half way through writing some of these features myself, but this saved me some work for sure.

**Comment by asdine** [comment]
The update calls don't get batched together, in fact [Batch is only useful when there are multiple goroutines calling it.](https://github.com/boltdb/bolt/blob/master/db.go#L634).
Replacing `Update` by `Batch` would kill the performances for the `Save` calls that are not concurrent.

Having a way to save concurrently (by integrating `Batch` to `Save` properly) would be great btw.

**Comment by Oregon-Tech-Ninja** [comment]
Would be great, I'm doing it quick and dirty for now. My local version has a BatchSave func and auto increments to generate ID's if they're empty. If I bother polishing it up any more, I'll give it a commit.

**Comment by asdine** [comment]
Sure. I am closing for now, don't hesitate opening again if you have something
