### ISSUE TITLE
PrefixScan and RangeScan scan also records

### ISSUE THREAD

**Issue by asdine** [asdine/storm#117]
`PrefixScan` and `RangeScan`should scan a node for matching buckets and return a slice of nodes.
Currently it scans also values saved in the bucket and therefore create nodes with the same name.

**Comment by bep** [comment]
Started to fix this ... but then, how do I identify a record? I tried to check the values in the range loop, but both cases is nil. Hmm...

**Comment by asdine** [comment]
Weird, normally to identify a record you just need to check if `v` is not nil in the loop.

**Comment by bep** [comment]
Yes, maybe I was tired ... I will check again.
