### ISSUE TITLE
storm discussions/questions (e.g. on a slack channel, etc.)

### ISSUE THREAD

**Issue by bits01** [asdine/storm#123]
Would you be open to creating a support/discussion channel on Slack for example where we can discuss and ask questions about storm and perhaps other projects you created?

BoltDB for example has a Slack channel here:
https://gophers.slack.com/messages/boltdb

Thank you.

**Comment by asdine** [comment]
Sure, it's a great idea! Let's do this! `storm` is of course already taken, so what about `stormbolt`, `stormlib`, `stormhq`... ?

**Comment by asdine** [comment]
I have created one called "stormbolt", if you have a better idea don't hesitate i'll rename it. https://gophers.slack.com/messages/stormbolt/

**Comment by bits01** [comment]
Thank you.

**Comment by bits01** [comment]
It would be useful to add a link to the README.md so others can find the channel too.

**Comment by asdine** [comment]
I think we should open a Gitter chat instead of a Slack channel, you don't necessarily need to signup to read the conversations and it has a better integration with Github IMO

**Comment by bits01** [comment]
My vote goes for the Slack channel, I like all the Go stuff in one place. Gitter is yet another client (or browser tab) to run.
But I'm OK with whatever you think works best for your project, as long as we have a single place.

**Comment by asdine** [comment]
I understand and i value your opinion, it's just that by experience and personal taste i prefer Gitter over Slack for library related discussion (as a user).

**Comment by bits01** [comment]
Gitter it is then. Just post the link in the README so we know where to find you :)

**Comment by asdine** [comment]
Done :)

**Comment by bits01** [comment]
https://gitter.im/asdine/storm
