### ISSUE TITLE
Iterate over keys in a bucket instead of fetching all

### ISSUE THREAD

**Issue by xor-gate** [asdine/storm#135]
I'm fearly new to BoltDB and Storm, but I'm concerned about memory consumption by fetching all keys in a bucket. As I'm going to store a jpg thumbnail per key and this can be >16k. 

You suggest in the readme:

```golang
var users []User
err := db.All(&users)
```

But this would fetch then all 16k keys (with thumbnails in my use case). 
Is there currently no way to iterate and execute a function per key?

**Comment by asdine** [comment]
You can use the `RawEach` method with `Select`

```go
db.Select().Bucket('User').RawEach(func(k []byte, v []byte) error {
  var u User
 err := db.Codec().Decode(v, &u)
 ...
})
```

It works but there should be a method for that i think.
Something like:

```go
  db.Select().Each(func(v interface{}) error {
    u := v.(*User)
    ...
  })
```

**Comment by xor-gate** [comment]
Yeah I understand I can use the lowlevel BoltDB access. But as you suggest a Each function would be wonderful!

**Comment by xor-gate** [comment]
Great, thanks for adding!
