### ISSUE TITLE
Document how to get storm annotations w/ protobuffers

### ISSUE THREAD

**Issue by vgough** [asdine/storm#138]
The protobuf example has a "storm" annotation in the generated pb.go file, but it isn't clear how this file is being generated - and how the storm annotation is being placed there.  Hopefully this generated file was not edited by hand, but that's the impression it leaves.  If that is the case, it would be better to automate this, perhaps using a tool such as https://github.com/favadi/protoc-go-inject-tag

**Comment by asdine** [comment]
Good idea! Actually for my other projects i'm already using https://github.com/favadi/protoc-go-inject-tag which is awesome for that. I should definitely add that to the readme

**Comment by asdine** [comment]
Done :) https://github.com/asdine/storm#marshalunmarshaler
