### ISSUE TITLE
new go get issue

### ISSUE THREAD

**Issue by everdev** [asdine/storm#144]
I did a new `go get` on bolt today, then ran `go get github.com/asdine/storm` just now and got back:

```
../github.com/asdine/storm/node.go:106: n.s.Bolt.Batch undefined (type *bolt.DB has no field or method Batch)
```

**Comment by bclermont** [comment]
https://github.com/boltdb/bolt/blob/master/db.go#L660

```
go get -u github.com/boltdb/bolt
```

**Comment by everdev** [comment]
Thank worked, thanks!
