### ISSUE TITLE
Queries and key names

### ISSUE THREAD

**Issue by mickep76** [asdine/storm#145]
Would be nice to be able to query using the key names from the JSON tag. esp. when doing REST API's.

Second when the name is incorrect it will segfault with:

```
reflect: call of reflect.Value.Interface on zero Value
```

This should probably return an error instead of this.

**Comment by asdine** [comment]
Can you give an example of the failing test so i can try to reproduce it locally please?

**Comment by mickep76** [comment]
Hi,

Here is an example: https://github.com/mickep76/storm_bug

**Comment by asdine** [comment]
Thank you, the bug has been fixed. `Select` now returns an error `q.ErrUnknownField` when the field is not found.

**Comment by asdine** [comment]
> Would be nice to be able to query using the key names from the JSON tag. esp. when doing REST API's.

Concerning this, i don't think this is a good idea to mix transport logic with database logic. A lot of people don't use Storm with a REST api (cli tools, gRPC, etc)
