### ISSUE TITLE
Transactions with multiple nodes

### ISSUE THREAD

**Issue by pdf** [asdine/storm#146]
The current transaction API doesn't appear to provide any way to use a transaction across multiple nodes without going directly to BoltDB.  `Begin` returns a `storm.Node`, with the transaction stored on a private field, but `WithTransaction` only accepts a `*bolt.Tx`, and there's no way to get at the transaction.

Ideally, either `Begin` would have returned a `*bolt.Tx`, or `WithTransaction` would have taken a `storm.Node`, and copied the `*bolt.Tx` from the passed node to the returned node, though the latter would require some method to get at the transaction anyway.

The cleanest way I can see to sort this out is to add a `Transaction() *bolt.Tx` method to Node, etc.  Thoughts?

**Comment by asdine** [comment]
Can you describe a use case where you'd need to pass a transaction to an already existing `Node` please?

The way i designed them was to be used like this:

```go
tx, _ := db.Begin()
tx.Save(...)

...
n := tx.From("a", "b", "c") // inherits the transaction
n.Save(...)

...
_ := tx.Commit()
```

but i'm open to discuss about other use cases

**Comment by pdf** [comment]
In my use-case, I pre-register a node, and return it via a lookup, so the hierarchy is not known from the call site, making it awkward to build from the root, something like:

```go
type nodeFunc func(enumValue) storm.Node
```

So, a transaction may be started from a nested node, but may need to be applied to some adjacent node without rebuilding the hierarchy.

```go
// Buckets related to enumValue1 and enumValue2 may be arbitrarily 
// nested under different hierarchies that are opaque at the call site, and
// where the root node may not be accessible
nestedNode := nodeFunc(enumValue1)
tx, _ := nestedNode.Begin(true)
_ = tx.Update(...)
_ = doSomethingWith(tx)
_ = tx.Commit()

func doSomethingWith(tx storm.Node) error {
  // With the proposed change, this is possible, otherwise requires the
  // transaction to have been started from the root node, and for the nested
  // node to be built from the root
  tx = nodeFunc(enumValue2).WithTransaction(tx.Transaction())
  return tx.Update(...)
}
```

Does that use-case make sense?  Not being able to apply a transaction to sibling nodes unless you start from the root feels rather awkward.

The transaction inheritance pattern you've described was not immediately apparent to me, so I can now see a possible alternative architecture for my use-case, where transactions are always started from the root, and instead of storing nodes, I generate factory functions with an optional transaction to return a node.

I can understand if you're reluctant to modify a public interface, so if you're not keen to take this on for that reason, or the example scenario above is not compelling, I'm happy to try the alternative arch to see if it can satisfy my existing scenarios.

**Comment by asdine** [comment]
`n.Begin` always calls the root node because since in BoltDB transactions are global, there are no difference between a transaction created from the root storm db object or from any nested node.
Transaction don't have to be started from the root, if you want to use a transaction for two siblings you just need to start by their closest parent.

Also Nodes are immutable, every call to `From` or `With*` returns a copy of the Node and the copy is cheap, so pre-creating or reusing a Node is useless. This was decided so `Node` would be thread-safe.
Nodes are meant to be used in a certain context (within a transaction for example) and then dropped.

I'm not sure we should expose too much the internals of a Node actually, i'm afraid it would make `Node` too confusing.

Creating the transaction from the root `db` and pass it to your factory func + the enum seems like a reasonable option, please try that and tell me if it works for you.

**Comment by pdf** [comment]
>  if you want to use a transaction for two siblings you just need to start by their closest parent

This requires knowledge at the call site of the hierarchy though, and that the transaction is always started from the right depth, which doesn't feel right - I should always be able to re-use a transaction from where it's created.

>  the copy is cheap, so pre-creating or reusing a Node is useless.

Yeah, retaining the node wasn't really about cost (though the registry does cache a bunch of reflection results for relational fields, joins, and similar), but about providing a cleaner abstraction/API.

I think my issue is mainly that the API feels wrong.  I think `Begin` at least probably shouldn't exist on `storm.Node` without some way to re-use the transaction sensibly.  If it only existed on `*DB`, it would force the usable pattern.

I will try the factory pattern instead, and re-open if I can't make it work.
