### ISSUE TITLE
Highly Available Storm

### ISSUE THREAD

**Issue by mofax** [asdine/storm#156]
I am checking out storm for a metadata service we need to setup; one hard requirement though, is high availability. 
This would mean some sort of master-follower replication.
Is this possible with storm?

**Comment by asdine** [comment]
Storm doesn't provide that as it's out of its scope but you can mix it with the [Raft](https://github.com/hashicorp/raft) protocol and get high availability.
There is already a BoltDB implementation [here](https://github.com/hashicorp/raft-boltdb) that you can use directly or read to implement yours with Storm.
