### ISSUE TITLE
Semantics of storm.Update ?

### ISSUE THREAD

**Issue by bradacina** [asdine/storm#160]
Hi there,
The Update() method fails for me and I'm not sure if I'm missing some obvious semantics. 

I have the following unit test method added to store_test.go

`
func TestUpdateSpecial(t *testing.T) {
	db, cleanup := createDB(t)
	defer cleanup()

	type User struct {
		ID        int    `storm:"id,increment"`
		Email     string `storm:"unique"`
		Password  []byte
		IsAdmin   bool
		IsDeleted bool
	}

	err := db.Save(&User{
		ID:        0,
		Email:     "test@test.com",
		Password:  []byte{1, 2, 3, 4, 5},
		IsAdmin:   false,
		IsDeleted: true})
	assert.NoError(t, err)

	u2 := User{
		ID:        1,
		Email:     "test@test.com",
		Password:  []byte{6, 7, 8, 9},
		IsAdmin:   false,
		IsDeleted: false}

	err = db.Update(&u2)
	assert.NoError(t, err)

	var u User
	err = db.One("ID", 1, &u)
	assert.NoError(t, err)
	assert.Equal(t, u.IsDeleted, u2.IsDeleted) // fails here, u2 did not get saved in the db
}
`
what am I missing?

Thank you in advance.

**Comment by asdine** [comment]
`Save` can be used to store a new version of your object under the same ID. `Save` actually **replaces** the entire record with the new one.

```go
u := User{
  Email:     "test@test.com",
  Password:  []byte{1, 2, 3, 4, 5},
  IsAdmin:   false,
  IsDeleted: true}

err := db.Save(&u)

u.Password = []byte{6, 7, 8, 9}
u.IsDeleted = false

err := db.Save(&u)
```

`Update` only updates fields with non-zero values. It should be used only to update **some** fields.
Example:

```go
db.Update(&User{ID: 1, Password: []byte{6, 7, 8, 9}, Email: "test2@test.com"})
```

If you need to update zero values, you can use the [`UpdateField`](https://godoc.org/github.com/asdine/storm#DB.UpdateField) method.

```go
db.UpdateField(&User{ID: 1}, "IsDeleted", false)
```

**Comment by bradacina** [comment]
Cool. Thank you for the explanation.

**Comment by drauschenbach** [comment]
Is this still true? "Save can be used to store a new version of your object under the same ID."

I get ErrAlreadyExists when I call Save for an existing id. And that calls for Upsert support that I don't yet see.

**Comment by asdine** [comment]
> I get ErrAlreadyExists when I call Save for an existing id
Can you provide an example please ?

> And that calls for Upsert support that I don't yet see.
Yes this would be interesting 👍

**Comment by drauschenbach** [comment]
My mistake... in writing the test I see that the ErrAlreadyExists is caused by a unique index constraint.

So given the current Save semantics, no Upsert is necessary since Save is already that.
