### ISSUE TITLE
Support compression

### ISSUE THREAD

**Issue by F21** [asdine/storm#161]
BoltDB does not have any compression and depends on the user to perform compression on data.

Since storm is a very comprehensive toolkit on top of BoltDB, supporting compression out of the box might be a good fit. For example, there's a go implementation of snappy: https://github.com/golang/snappy

**Comment by ZenLiuCN** [comment]
I choose codec msgpack as storm codec ,It's only about 40% size of orginal json data, and for files compress before put into struct.
ps: I don't think compression is main functional of storm

**Comment by F21** [comment]
@ZenLiuCN Good point. I created a custom codec using msgpack and the file size appears to be smaller. I have not tried using snappy yet, but I believe that should bring further space savings.

**Comment by bep** [comment]
Note that Storm already have a codec for MessagePack, see https://godoc.org/github.com/asdine/storm/codec/msgpack

It was missing in the README (just added).
