### ISSUE TITLE
Using concurrent writers and batch

### ISSUE THREAD

**Issue by F21** [asdine/storm#163]
I am parsing a 1.3GB CSV file with 11,422,254 lines/records and loading it into BoltDB using storm. I have a goroutine which reads a line from the file and pushes it to a channel. I then spawn 4000 go routines to parse the line, convert it to the appropriate structure and save it to the db.

I open the database using `storm.Open(pathToMyDB, storm.Batch())` to create a db instance. This instance is then passed to each go routine, which calls `db.Save(recordToInsert)`.

Performance is definitely better than just having 1 writer, but it still seems to be taking a while: more than an hour and the process is still going.

Is this the right way to use batch writes? When using batch writes, how many records are batched together per write?

**Comment by bep** [comment]
>When using batch writes, how many records are batched together per write?

There is no such logic in Storm; you must yourself partition the updates into transactions, setting batch mode only instructs Storm to use `db.Batch` in BoltDB instad of `db.Update`( see https://github.com/boltdb/bolt#batch-read-write-transactions).

**Comment by F21** [comment]
Do you mean that I would need to use the bolt instance in `DB.Blot` directly? In this case, that means I would need to create indexes and other bits of storm functionality manually, right?

**Comment by bep** [comment]
>Do you mean that I would need to use the bolt instance in DB.Blot directly

No, I mean that you should really ask the `BoltDB` project to get the internals of how batch updates work.

**Comment by F21** [comment]
Oh, ok. Cool, I'll see if I can find out if this is tunable within Bolt.

**Comment by bep** [comment]
But a tip would be to dramatically reduce the number of Go routines. Try 10 or something.

**Comment by F21** [comment]
I tried low numbers, but it was pretty slow. Performance increased when I increased the number of go routines, but after processing for a while, writing to the DB became slower and slower.
