### ISSUE TITLE
Moving to v1

### ISSUE THREAD

**Issue by asdine** [asdine/storm#169]
Storm has enough features for it to be useful for a majority of use cases, plus the database file structure has evolved pretty well.
I tried several times to implement properly some of the features requested in the issues but:
- the internals have become quite complex
- it's difficult to move without breaking either the API or the database file structure.

Instead of "suffering" from that, i think we should lock the database structure and the API. Storm is used in quite a few projects, ensuring a stable database is important.

What i propose is to:
- release a v1.0.0 where bug fixes and non breaking features would be released
- begin to think of a v2 where some design decisions could be fixed

**Comment by asdine** [comment]
I released the v1.0.0 🕺 https://github.com/asdine/storm/releases/tag/v1.0.0

**Comment by joeblew99** [comment]
is there anything yet about the v2 design architecture ?

**Comment by asdine** [comment]
@joeblew99 Sorry i was on holiday 🙈 . I'm still brainstorming and gathering ideas based on usage and unclosed issues, i will present a doc when i'll have some time so anyone could give his opinion before started the actual implementation. In the meantime, if you have something to propose please do 👍
