### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kristjank** [asdine/storm#175]
What is the best way to do an equivivalent to select max(column) from table..
i.e. if table has million of records - i just want one record that is max value in xx_column

**Comment by asdine** [comment]
If your field is indexed you could use `AllByIndex ` + `Reverse`

```go
type User struct {
  ID int
  Age int `storm:"index"`
}

var users []User
db.AllByIndex("Age", &users, storm.Limit(1), storm.Reverse())
```

**Comment by kristjank** [comment]
a nice... I did it with:
`query = DB.Select().OrderBy("Height").Reverse()
err = query.First(&lastBlock)`

which is better performance wise... or no difference... as this method will be called many times...

And thank you for your great work on STORM :)!!!!!

**Comment by asdine** [comment]
I'm not sure that using `Select` with `OrderBy` will give good results in terms of performance.
`OrderBy` will force a full scan plus a sort which will take as much time as you have data in your bucket, something like O(n)

`AllByIndex` uses an index which is already sorted, and using `Reverse` + `Limit(1)` will make it only return the last element (O(1))

**Comment by kristjank** [comment]
Ty for this kind explanation. Using it as you suggested
