### ISSUE TITLE
Prefix scan on indexes?

### ISSUE THREAD

**Issue by bep** [asdine/storm#179]
Say I have 

```go
type file struct {
	Filename string `storm:"id"`
```
I know I can do

```go
q.Re("Filename", "^/somedir")
```

And I will get what I want, but it will be slowish for larger buckets.

I dont't think there is a way to do something ala `db.Prefix("Name", "/somedir")` using that index?

**Comment by asdine** [comment]
If we add the a `Prefix` method on indexes we might be able to tell `PrefixScan` to use it instead of scanning the whole bucket. We might need to rename `PrefixScan` into `Prefix` then. WDYT?

**Comment by bep** [comment]
>We might need to rename PrefixScan into Prefix then.

Sounds good to me.

**Comment by asdine** [comment]
Now that i think of it, it might not take much more time to also create a `db.Re("Name", "\\d+")` method which would use indexes when possible and use `Select(q.Re("Name", "\\d+"))` when no index is found.

**Comment by asdine** [comment]
> We might need to rename PrefixScan into Prefix then
I was wrong, `PrefixScan` is useful for getting a subset of buckets, it should stay.

**Comment by kenota** [comment]
@asdine 
This test case is failing for me on 2.0.1 unless i create index:

```go
package main

import (
	"io/ioutil"
	"os"
	"testing"

	"github.com/asdine/storm"
	"github.com/stretchr/testify/require"
)

type Entity struct {
	ID string `storm:"id"`
}

func TestPrefixScan(t *testing.T) {
	f, err := ioutil.TempFile("", "test")
	require.Nil(t, err)
	defer os.Remove(f.Name())

	db, err := storm.Open(f.Name())
	require.Nil(t, err)

	require.Nil(t, db.Init(&Entity{}))

	require.Nil(t, db.Save(&Entity{ID: "1"}))
	require.Nil(t, db.Save(&Entity{ID: "12"}))

	var res []*Entity
        // Getting  Expected nil, but got: &errors.errorString{s:"index not found"} here
	require.Nil(t, db.Prefix("ID", "1", &res))

}
```
