### ISSUE TITLE
Find() returns wrong result for Reverse() on index on some keys

### ISSUE THREAD

**Issue by abrander** [asdine/storm#184]
When using `Find()` combined with reverse *and* index, `Find()` will not return the
correct result set. I have made a minimal test showcasing the problem.

The really weird part is that this is only true for some values of the indexed member (!).

I have marked two lines with `HERE` - these can be changed to make the test behave as expected.

```go
package main

import (
	"fmt"
	"os"

	"github.com/asdine/storm"
)

type user struct {
	ID   uint64 `storm:"id,increment"`
	Slug string `storm:"index"` // HERE: Remove "index" and everything works.
}

var slug = "t" // HERE: Change this to "s" and everything works.

func main() {
	db, _ := storm.Open("testdb.db")
	defer db.Close()
	defer os.Remove("testdb.db")

	db.Init(&user{})

	save(db)
	find(db) // We expect ID 1
	save(db)
	find(db) // We expect ID 2
}

func save(db *storm.DB) {
	t1 := &user{Slug: slug}
	db.Save(t1)
	fmt.Printf("Saved ID %x\n", t1.ID)
}

func find(db *storm.DB) {
	var results []user

	err := db.Find("Slug", slug, &results, storm.Reverse())

	if err != nil {
		fmt.Printf("%s\n", err.Error())
	}

	if len(results) > 0 {
		fmt.Printf("Got ID %x\n", results[0].ID)
	}
}
```

I tried debugging the problem, but i got stuck in trying to understand how  `ListIndex.All()` and `internal.Cursor` interacts with `boltdb.Cursor`.

**Comment by asdine** [comment]
Thank you ! It was indeed a bug on indexes when using `Reverse`.
