### ISSUE TITLE
"Call of reflect.Value.Elem on struct Value" with Batch mode

### ISSUE THREAD

**Issue by oskarwojciski** [asdine/storm#185]
When I use Batch mode with concurrent insert/update/delete on the object with the same primary id, sometimes I got 

`panic: reflect: call of reflect.Value.Elem on struct Value`

### GO version

```go version go1.9 darwin/amd64```

### GO env

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/owojciski/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cs/x4k9_xc97yx98mttj_xg2n8w0000gn/T/go-build353069185=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### Code to replicate (might need few re-runs):

https://gist.github.com/oskarwojciski/9f3f9a4a11db7f4f01cc80d855616478

Without the Batch mode the issue doesn't appear

**Comment by asdine** [comment]
Thank you ! Found a weird race condition when reusing reflect.Value across goroutines.
