### ISSUE TITLE
db.One appends keys to map in target struct instead of recreating empty map

### ISSUE THREAD

**Issue by kenota** [asdine/storm#197]
**Summary**

It seems that if target struct for `db.One` has non-empty map, keys get added to that map instead of map being completely recreated

**Expected behaviour**

I would expect that `db.One` should put target struct fields in same state as they were when struct was saved.

**Observed behaviour**

In case of maps, if target struct already has map with some keys, they will not be removed. 

**Steps to reproduce**

1. Store struct which has map field and one key. 
2. Declare a variable of same type having map initialised with different key compared to stored one
3. Load from storage to variable defined in pt 2
4. Observe that after load, map will have both keys, stored from pt1 and from target in pt2

Code which demonstrates the problem:
```go
type Entity struct {
	ID    string `storm:"id"`
	Map   map[string]bool
	Slice []int
}

func TestMapLoading(t *testing.T) {
	f, err := ioutil.TempFile("", "test")
	require.Nil(t, err)

	db, err := storm.Open(f.Name())
	require.Nil(t, err)
	defer func() {
		db.Close()
		os.Remove(f.Name())
	}()

	const MAP_KEY = "1"
	const ID = "objid"
	require.Nil(t, db.Save(&Entity{
		ID:  ID,
		Map: map[string]bool{MAP_KEY: true},
	}))

	existingObj := Entity{
		Map: map[string]bool{"2": true},
	}

	require.Nil(t, db.One("ID", ID, &existingObj))
        // next assertion fails because map has both "1" and "2" keys
	require.Equal(t, 1, len(existingObj.Map))   
	_, found := existingObj.Map[MAP_KEY]
	require.True(t, found)
}
```

I am not sure if this is happening with other methods, I happened to use `db.One` and stumbled upon this issue.

Also, It **does not** seem to be the case with slices, similar test working fine for slices, it will have only one element after load.

**Comment by asdine** [comment]
This behaviour doesn't come from Storm actually, but from the underlying codec used to encode/decode entities (see https://github.com/asdine/storm#marshalunmarshaler).
By default, Storm uses the stdlib json codec which has the behaviour you describe, here is go playground example https://play.golang.org/p/h3CdeSUHxW_M.

If this behaviour isn't what you expect you have several choices though.
- Keep using the json codec but implement the [`json.Unmarshaler`](https://golang.org/pkg/encoding/json/#Unmarshaler) interface
- Use another codec, https://github.com/asdine/storm#provided-codecs
- Implement your own codec

**Comment by kenota** [comment]
@asdine I see. Thank you for such quick response! Do you by chance know which codec does not behave in this way? 

It might be great to add this to readme as a warning. Perhaps it can be  common to reuse some existing struct with map when loading structs. This can lead quite tricky bugs. I've actually stumbled upon this when my test case was failing where I thought it should not :)

**Comment by asdine** [comment]
> Do you by chance know which codec does not behave in this way?

The gob decoder has the same behaviour (https://play.golang.org/p/QXsQ1b6DRTZ), i don't know about the others for this specific use case.
I suggest using the `json.Unmarshaler` interface and simply cleanup the map before unmarshaling it: https://play.golang.org/p/_wEvP9-oQIP

> It might be great to add this to readme as a warning. Perhaps it can be common to reuse some existing struct with map when loading structs. This can lead quite tricky bugs. I've actually stumbled upon this when my test case was failing where I thought it should not :)

Good idea 👍
