### ISSUE TITLE
Save for an array, aka bulk insert

### ISSUE THREAD

**Issue by tandr** [asdine/storm#203]
Folks,
"Save" can only commit one structure at the time, and (in my case) after reaching 100k-150k items it becomes unbelievable slow (takes 3 min for 100k items, 4 hours 35min for 1mil). Is there a way to insert a slice of items at the time (each item contains auto-increment field). Something like SaveBulk([]interface{}), that does it in one shot to speed it up?
The readme and examples are only saving one thing at the time, sorry.

**Comment by asdine** [comment]
Did you try using [manual transactions ](https://github.com/asdine/storm#transactions) ?

**Comment by tandr** [comment]
I will try and report back, thank you!

**Comment by tandr** [comment]
:( I split 100k insert into 10k batches - pretty much the same time (3min30 vs 3min41sec - I would say round error)

**Comment by tandr** [comment]
Oops, found an error, batches were smaller. Will rerun

**Comment by tandr** [comment]
Ok, for batches of 1000, 100k improved to 3min 15sec from 3min 41 sec. Better, but the time goes up with each slice inserted, so I am not going to try 1mil right now.

Is it possible pre-grow database file to what I think it will be?

**Comment by asdine** [comment]
> Is it possible pre-grow database file to what I think it will be?

Not that i'm aware of.

3m15 seems a lot, could you provide a working example of the operations you perform please ?
Before giving you advices i need to understand what you are doing

**Comment by tandr** [comment]
It is eval/perf testing right now for our small backend service that now need a db.  It is trying to emulate real data.

Import 298k JSON file with array of 63 items (which contains subarray of 3 other items up to 2 level deep),  and trying to insert it over and over into bucket incrementing ID field until I have 100k (or 1mil) uniques keys in DB, then run some queries.

**Comment by asdine** [comment]
Some ways you can improve performance:
- Use another codec. The default is JSON, with Protobuf for example you can achieve much better perfs. (https://github.com/asdine/storm#provided-codecs)
- Less indexes mean faster writes
- If your design allows you to execute writes concurrently, activate the [`Batch()` mode](https://github.com/asdine/storm#batch-mode)

**Comment by tandr** [comment]
Closing as duplicate of #176
