### ISSUE TITLE
NotIn()?

### ISSUE THREAD

**Issue by davidrenne** [asdine/storm#212]
I see we have a 

`func In(field string, v interface{}) Matcher {`

What would be the equivalent of selecting all but NotIn a list?

**Comment by asdine** [comment]
You can combine [`Not`](https://godoc.org/github.com/asdine/storm/q#Not) with `In`.

```go
db.Select(
  q.Not(q.In("A", []int{1,2,3}))
)
```

**Comment by davidrenne** [comment]
Thank you!
