### ISSUE TITLE
OrderBy and Reverse for 2 different columns

### ISSUE THREAD

**Issue by errashe** [asdine/storm#214]
In my program i need just sort one column by two different reverses. Like

```GO
db.Select().OrderBy("Priority", "Timestamp").Reverse().Find(&servers)
```

And servers with priority should be first in list, and then any other servers according to timestamp. But i can reverse or not only both of this columns - so i can sort only by prior or time in one query...

```GO
db.Select().OrderBy("Priority", "Timestamp").Reverse().Find(&servers)
```
```
localhost       | 19728.75/12045.97 mbit/s |    0.46 ms | 03-04-2018 10:02:31 +
some.ru         |     0.00/    0.00 mbit/s |    0.00 ms | 03-04-2018 10:03:44 -
127.0.0.1       | 23943.74/14376.69 mbit/s |    0.21 ms | 03-04-2018 10:02:30 -
```

```GO
db.Select().OrderBy("Priority", "Timestamp").Find(&servers)
```
```
127.0.0.1       | 23943.74/14376.69 mbit/s |    0.21 ms | 03-04-2018 10:02:30 -
some.ru         |     0.00/    0.00 mbit/s |    0.00 ms | 03-04-2018 10:03:44 -
localhost       | 19728.75/12045.97 mbit/s |    0.46 ms | 03-04-2018 10:02:31 +
```

But i need prior servers first, and then everything else in timestamp sorted condition.
```
localhost       | 19728.75/12045.97 mbit/s |    0.46 ms | 03-04-2018 10:02:31 +
127.0.0.1       | 23943.74/14376.69 mbit/s |    0.21 ms | 03-04-2018 10:02:30 -
some.ru         |     0.00/    0.00 mbit/s |    0.00 ms | 03-04-2018 10:03:44 -
```

Is it possible?

**Comment by errashe** [comment]
Ok, i found solution, but it's a bit strange, so i need to reverse my priority values to "normal" sorting...

**Comment by asdine** [comment]
I can't reproduce on my computer, can you provide a working example ? (a `main` function with some fake data)

**Comment by errashe** [comment]
```GO
type Server struct {
	ID        int `storm:"id,increment"`
	IP        string
	Priority  int
	Timestamp time.Time
}

var err error

func main() {
	db, err := storm.Open("my.db")
	defer db.Close()
	if err != nil {
		Println(err)
	}

	db.Init(new(Server))

	db.Save(&Server{IP: "first", Priority: 0, Timestamp: time.Now()})
	db.Save(&Server{IP: "second", Priority: 1, Timestamp: time.Now().Add(time.Minute)})
	db.Save(&Server{IP: "third", Priority: 0, Timestamp: time.Now().Add(2 * time.Minute)})

	var servers []Server
	if err = db.Select().OrderBy("Priority", "Timestamp").Reverse().Find(&servers); err != nil {
		Println(err)
	}

	for _, server := range servers {
		Println(server)
	}

}
```

And now, if i change order position - i can get wrong order, or unchangable order (if ordered by prior, timestamp doesn't change nothing), or ordered only by one column, and then i need to take last if it's prior, or first, if not. 

Looks bad, for me.

**Comment by asdine** [comment]
When i use your example i get the correct order even if i change the values, i don't really understand what's not working here.

Can you provide some queries + their output please ?

Here's what i got:

```go
db.Save(&Server{IP: "first", Priority: 0, Timestamp: time.Now()})
db.Save(&Server{IP: "second", Priority: 1, Timestamp: time.Now().Add(time.Minute)})
db.Save(&Server{IP: "third", Priority: 0, Timestamp: time.Now().Add(2 * time.Minute)})

db.Select().OrderBy("Priority", "Timestamp").Reverse().Find(&servers)

/* output
{2 second 1 2018-04-03 13:38:15.790201429 +0200 CEST}
{3 third 0 2018-04-03 13:39:15.793199457 +0200 CEST}
{1 first 0 2018-04-03 13:37:15.781850035 +0200 CEST}
*/
```

```go
db.Save(&Server{IP: "first", Priority: 0, Timestamp: time.Now()})
db.Save(&Server{IP: "second", Priority: 1, Timestamp: time.Now().Add(time.Minute)})
db.Save(&Server{IP: "third", Priority: 1, Timestamp: time.Now().Add(2 * time.Minute)})

db.Select().OrderBy("Priority", "Timestamp").Reverse().Find(&servers)

/* output
{3 third 1 2018-04-03 13:41:35.072129132 +0200 CEST}
{2 second 1 2018-04-03 13:40:35.069081712 +0200 CEST}
{1 first 0 2018-04-03 13:39:35.064165334 +0200 CEST}
*/
```

Can you provide the same kind of examples as above so i can compare on my laptop ?

Also, what version of Storm are you using ?

**Comment by errashe** [comment]
Yea, man, it works EXACTLY the same, but I need something else, i need order by Priority and then order reverse by timestamp. I need all prioritized old servers :D

**Comment by errashe** [comment]
Missclicked...

**Comment by errashe** [comment]
I need this kind of output
/* output
{2 second 1 2018-04-03 13:38:15.790201429 +0200 CEST}
{1 first 0 2018-04-03 13:37:15.781850035 +0200 CEST}
{3 third 0 2018-04-03 13:39:15.793199457 +0200 CEST}
*/

And if none priority servers - everything should be just sorted by timestamp.

**Comment by errashe** [comment]
What i want to do in sql looks like:
```SQL
SELECT * FROM (SELECT * FROM `servers` ORDER BY 'Priority" DESC) ORDER BY 'Timestamp';
```

**Comment by errashe** [comment]
Yep, this answer i expected, ok then, now i know for sure. Thank you for help.
