### ISSUE TITLE
Unique constraint using multiple columns

### ISSUE THREAD

**Issue by vishr** [asdine/storm#215]
Do you plan to provide unique constraint using multiple columns?

**Comment by asdine** [comment]
They are already supported actually, you can use a nested struct for that:

```go
package main

import (
	"fmt"

	"github.com/asdine/storm"
)

type User struct {
	ID   int `storm:"id,increment"`
	Uniq struct {
		A string
		B int
	} `storm:"unique"`
}

func main() {
	db, err := storm.Open("my.db")
	if err != nil {
		panic(err)
	}

	var u User

	u.Uniq.A = "a"
	u.Uniq.B = 1

	err = db.Save(&u)
	if err != nil {
		panic(err)
	}

	u.ID++
	err = db.Save(&u)
	fmt.Println(err)
}
```

**Comment by vishr** [comment]
Thanks for your response. The structure is actually flat, does embedded struct works? Other option I was thinking is to add another field `Unique` which is a combination of multiple columns values.

**Comment by asdine** [comment]
For nested structs you can use the `inline` option which allows the usage of the storm tag in nested structs.

```go
type User {
  ID string
  Flattened struct {
    A string `storm:"unique"`
    B uint
  } `storm:"inline"`
}
```

This can be combined with the `unique` constraint in a deeply nested struct

```go
type User {
  ID string
  Flattened struct {
    A string
    B struct {
      C int
      D struct
    } `storm:"unique"`
  } `storm:"inline"`
}
```

> Other option I was thinking is to add another field Unique which is a combination of multiple columns values

This works too, you can add a dedicated field for that if you prefer a flat struct.

**Comment by vishr** [comment]
The above didn't work and I went through the route of creating a composite field.
