### ISSUE TITLE
Cannot update object

### ISSUE THREAD

**Issue by halink0803** [asdine/storm#221]
I tried to  update an object with Update function, but it does not update. Any ideas why this happen. The function does not respond any error.

Here is the code:

```
	var score Score
	err := self.db.One("TelegramID", userID, &score)

	if err == storm.ErrNotFound {
		log.Printf("%+v", newScore)
		err := self.db.Save(&newScore)
		if err != nil {
			log.Printf("Cannot save score: %s", err.Error())
		}
	} else {
		log.Printf("%+v", newScore)
		err := self.db.Update(&newScore)
		if err != nil {
			log.Printf("Cannot update score:  %s", err.Error())
		}
	}
```

Thank you in advance.

**Comment by asdine** [comment]
Can you describe what's inside `newScore` ?

**Comment by halink0803** [comment]
Here is Score object:

```
type Score struct {
	ID          int `storm:"id"`
	Score       int
	UserName    string
	FirstName   string
	LastName    string
	LuckyNumber string `storm:"index"`
}
```

I change One function from looking for TelegramID to looking for ID, then it works.

**Comment by asdine** [comment]
So there is no issue ?

**Comment by halink0803** [comment]
Yep, it used to have an issue but I don't know why it failed. I just know it works now.

Thank you,

**Comment by halink0803** [comment]
I found the issue again. It cannot update an int value back to 0. First, I change score, save it, then update it back to 0 and it does not update. Is this an issue? @asdine

**Comment by asdine** [comment]
`Update` only updates non zero values, if you need need to set something to a zero value use `UpdateField`

```go
err := db.UpdateField(&User{ID: 10}, "Age", 0)
```

**Comment by halink0803** [comment]
@asdine Thank you for your answer. Maybe I misreading the documentation.
