### ISSUE TITLE
List index?

### ISSUE THREAD

**Issue by gkze** [asdine/storm#234]
I have a struct with a field the value of which is a list of strings. The use for this field is to retrieve objects which have a string in the list field.

What is the best way to do this? I am not sure.

**Comment by asdine** [comment]
Can you provide an example of a structure please?

**Comment by gkze** [comment]
```go
type Object struct {
    field1 string
    field2 []string
}
```

Is there a way to only retrieve objects that have a certain string present in `field2`?

**Comment by malaschitz** [comment]
For example I have structure:

type File struct {
 fileName string `storm:"id"`
 fileData []byte
}

Is there possibility retrieve only indexes (FileNames) ??

**Comment by gkze** [comment]
Thanks! Sorry for letting this stay open this long.
