### ISSUE TITLE
About storage speed

### ISSUE THREAD

**Issue by garytone** [asdine/storm#235]
My application scenario is to frequently import data into various types of objects. However, after simple testing, the writing speed is not optimistic. I saw your answer to this question in another question, but that scenario was to write a portion of the data in bulk. I have thought about accumulating data to a certain amount and then writing it in batches. But the write may fail and can't satisfy my application scenario, so is there any way to improve the write speed of the database? Thank you

**Comment by asdine** [comment]
Most of the time spend writing is done by the Bolt library. Bolt is an ACID database and this kind of guarantees come with (write) performance cost.

> But the write may fail and can't satisfy my application scenario

Can you elaborate? If i'm not wrong, if the write fails, nothing is written on disk. Only parts of the transaction can be replayed multiple times, but in the end if the batch succeeded that means everything has been written correctly.

**Comment by garytone** [comment]
It should be that I am not using it properly. I thought of a way to use it. In the middle layer, use storm.Node. Let me test it and see the effect. Thank you very much for your reply.
