### ISSUE TITLE
`storm:"id"` not working as expected

### ISSUE THREAD

**Issue by jpo-joyent** [asdine/storm#241]
According to the docs:

https://github.com/asdine/storm/blob/5a6fe65e3993f63951c8e3f64c812536c9e23595/README.md#L97-L111

I believe the following should work

```go
package main

import (
	"fmt"

	"github.com/asdine/storm"
)

type Inlined struct {
	foo string `storm:"id"`
}

type Schema struct {
	child Inlined `storm:"inline"`
	bar string
}

func main() {
	db, err := storm.Open("./test.db")
	if err != nil {
		fmt.Println("unable to open db:", err)
	}

	if err := db.Init(&Schema{}); err != nil {
		fmt.Println("unable to init db:", err)
	}
}
```

but instead I get:
```
$ go run ./test.go
unable to init db: missing struct tag id or ID field
```

I also get the same result with:
```go
type Schema struct {
	Inlined `storm:"inline"`
	bar string
}
```

Did I misread the docs? Is this functionality broken? Are the docs wrong?

**Comment by jpo-joyent** [comment]
Actually, even the simplest example of an explicit `id`:

```go
package main

import (
	"fmt"

	"github.com/asdine/storm"
)

type Schema struct {
	bar string
	foo string `storm:"id"`
}

func main() {
	db, err := storm.Open("./test.db")
	if err != nil {
		fmt.Println("unable to open db:", err)
	}

	if err := db.Init(&Schema{}); err != nil {
		fmt.Println("unable to init db:", err)
	}
}
```

seems to be broken:
```
$ go run ./test.go 
unable to init db: missing struct tag id or ID field
```

**Comment by jpo-joyent** [comment]
Oops, good catch. I evidently introduced that separate error in trying to reduce this from a larger test case. That's not what I was trying to demonstrate, haha.

A more accurate test case reduction is the following:
```go
package main

import (
	"fmt"

	"github.com/asdine/storm"
)

type Inlined struct {
	Foo string `json:"foo" storm:"id"`
}

type Schema struct {
	Child []Inlined `json:"asdf" storm:"inline"`
	Bar string
}

func main() {
	db, err := storm.Open("./test.db")
	if err != nil {
		fmt.Println("unable to open db:", err)
	}

	if err := db.Init(&Schema{}); err != nil {
		fmt.Println("unable to init db:", err)
	}
}
```

It seems obvious now that the issue is likely that I'm trying to put the ID within an array, and multiple primary keys per entry may violate internal invariants. Is this the case?

**Comment by jpo-joyent** [comment]
Yeah, seems like the case.

non-marshaled ID at the top-level works as expected:
```go
type Schema struct {
	ID `json:"-"`
	Children []Inlined `json:"asdf"
	// ...
}
```

**Comment by jpo-joyent** [comment]
@asdine Thank you for catching my dumb mistakes :)

**Comment by jpo-joyent** [comment]
Same problem for pointers to structs. They really have to be only anonymous inlined structs, no indirection.

**Comment by asdine** [comment]
You can't have slices of inlined structs, this can't work because the tags will be repeated on every value in the slice.
