### ISSUE TITLE
release tag needed with new go.mod

### ISSUE THREAD

**Issue by chappjc** [asdine/storm#244]
Thanks for adding the go.mod, which makes it trivial to use storm with the intended dependencies in my module-enabled app.  However, since storm has no semver tagged versions since adding go.mod, storm gets included with a "pseudo-version" like:

```
github.com/asdine/storm v0.0.0-20181222204021-f4de09a602e2
```

Please tag a semver release, `v2.1.3` maybe, so that importers will stick to tagged releases of storm when updating their module dependencies.

**Comment by asdine** [comment]
Done :+1: https://github.com/asdine/storm/releases/tag/v2.1.3

**Comment by chappjc** [comment]
Thank you!
