### ISSUE TITLE
OrderBy not working correctly

### ISSUE THREAD

**Issue by artvel** [asdine/storm#247]
Reproducible with `time.Time` and `Select` with or without `q.Re` and with or without `Reverse()`.
```
	Item struct {
		ID     string `json:"id" storm:"id"`
		Name   string `json:"name" storm:"index"`
		Detail string `json:"detail"`
		Updated time.Time `json:"updated" storm:"index"`
		Created time.Time `json:"created" storm:"index"`
	}

func queryAll(contains string) ([]*Item, error){
	var items []*Item
	db.Select(q.Or(
	q.Re("Name", contains),
	q.Re("Detail", contains))).Limit(20).
	Skip(10).
	OrderBy("Created").
	Reverse().
	Find(&items)
	return items, nil
}
```

Any help appreciated.

Thanks!

**Comment by artvel** [comment]
@asdine any chance that this is going to be considered?
Let me know, in case I can be of any help.

**Comment by gnur** [comment]
I just ran into this exact issue, great to see there already is an PR addressing it, much cleaner then making an additional string timestamp column to sort on.

**Comment by asdine** [comment]
Thank you @artvel, sorry for the delay :pray:
