### ISSUE TITLE
Support Sereal versioning

### ISSUE THREAD

**Issue by bep** [asdine/storm#25]
I notice Sereal versions their codec, current at version 3. 

I suggest we make sure that the current /sereal package goes against version 3 (use the `NewEncoderV3`etc.) -- and if there is any interesting development in this area in the future, add /sereal4 or whatever.

**Comment by bep** [comment]
Thinking a little, I think it is cleanest if we renames the current package to /sereal3. That will make everything perfectly clear, and will room for an  unlikely /sereal2.

**Comment by bep** [comment]
I think I changed my mind on this ... Although the encoders are versioned (1,2 and 3) the decoder handles all 3. So I'll assume that a 4th version added will be "better" and handled fine by the decoder, so from Storm's perspective the current code would be the best and simplest for most people. 

Closing this. Please reopen if you disagree.

**Comment by asdine** [comment]
I agree with you and i trust your expertise
