### ISSUE TITLE
must use semantic import versioning

### ISSUE THREAD

**Issue by chappjc** [asdine/storm#255]
With Go 1.13 and the {proxy,sum}.golang.org services, it is no longer allowed to have a go.mod that does not use semantic import versioning but has a v2+ semantic version tagged.

https://sum.golang.org/lookup/github.com/asdine/storm@v2.2.0+incompatible

> not found: github.com/asdine/storm@v2.2.0+incompatible: invalid version: +incompatible suffix not allowed: module contains a go.mod file, so semantic import versioning is required

What is needed is for storm to define it's modules in go.mod as:

```
module github.com/asdine/storm/v3

...
```

And then create a v3.0.0 tag.

Please see https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher for details.

**Comment by navono** [comment]
Any progress?

Currently, it seems cann't install latest version.

**Comment by chappjc** [comment]
@navono It's resolved in https://github.com/asdine/storm/issues/256.  Just to be merged and tagged

**Comment by Xe** [comment]
@asdine can you please tag version 3.0.0?

**Comment by asdine** [comment]
Done 👍 Sorry for the delay
