### ISSUE TITLE
Update to bolt v1.3.4 for go 1.14 unsafe pointer conversion fixes

### ISSUE THREAD

**Issue by jack-kelly** [asdine/storm#265]
Running built in race detection will error on unsafe pointer conversions in the <1.3.4 bolt codebase.

See https://github.com/etcd-io/bbolt/pull/201 for the fix.

https://github.com/etcd-io/bbolt/releases/tag/v1.3.4

**Comment by asdine** [comment]
Awesome, I was waiting for that fix. Thank you!

**Comment by jack-kelly** [comment]
No problem!

**Comment by asdine** [comment]
Done https://github.com/asdine/storm/releases/tag/v3.1.1 thanks 👍
