### ISSUE TITLE
How to update an empty field of the struct? 

### ISSUE THREAD

**Issue by nicewook** [asdine/storm#269]
I made a struct User, and one of the fields is FirstName. 
What if I want to update the field value from "Tom" to "" (empty string)?

```
if err := db.Update(&user); err != nil {
	return errors.New("fail to update")
}
```

**Comment by nicewook** [comment]
If this is an issue, how about using `db.Save` instead of `db.Update` ?

**Comment by asdine** [comment]
You need to use `UpdateField` instead, `Update` skips zero values, `UpdateField` doesn't

**Comment by nicewook** [comment]
Thank you. Could you give me my idea of using db.Save() ? 
In case of update all the structure, then db.Save() would work.

**Comment by asdine** [comment]
Basically, `db.Save` replaces the entire record if it already exists.
So using db.Save works well if you fetched the record beforehand (using `db.One` or `db.Find`), but you need to do that within the same transaction to avoid race conditions.

```go
tx, err := db.Begin(true)
if err != nil {
  return err
}
defer tx.Rollback()

var u User
tx.One(...)

...


u.Name = ""
tx.Save(&u)

tx.Commit()
```
