### ISSUE TITLE
Does DeleteStruct look at more than the ID?

### ISSUE THREAD

**Issue by makeworld-the-better-one** [asdine/storm#274]
It'd be helpful to be able to delete objects without having load the whole object into memory. If I just have the ID of an object, can I delete it just based on that, or does `DeleteStruct` look at more? I was planning on creating an dummy object where only the ID is set, and then sending that to `DeleteStruct`.

**Comment by asdine** [comment]
You don't have to load the object in memory to delete it, you can use `DeleteStruct` like this:

```go
db.DeleteStruct(&Foo{ID: 1})
```

**Comment by makeworld-the-better-one** [comment]
Okay, that's exactly what I was planning on doing. Thanks! It'd be helpful to have this on the README maybe.
