### ISSUE TITLE
Field as bool, Update failed

### ISSUE THREAD

**Issue by zgwit** [asdine/storm#278]
As title.

My model:
`

type User struct {

	ID   int      `storm:"increment" json:"id"`

	Name string   `json:"name"`

	Disabled bool `json:"disabled"`

}

`
1. Modify Disabled as false
2. Call db.Update(&user)
3. Call db.All(&users), Disabled is always true

**Comment by asdine** [comment]
`Update` only updates non-zero value fields, you need to use `UpdateField`. https://github.com/asdine/storm#update-an-object

**Comment by zgwit** [comment]
Operation：
 
true -> false
!0 -> 0
"xxx" -> ""

Must use UpdateField ?

**Comment by zgwit** [comment]
unreasonable

**Comment by asdine** [comment]
> Must use UpdateField ?

Yes.

> unreasonable

Closing this issue as this answers the question and that the response is rude. Don't hesitate to open it if you need more info AND if you change your behavior.

**Comment by skaldesh** [comment]
I had the same problem right now. Could we update the part of the README that you linked (https://github.com/asdine/storm#update-an-object) so that it says so directly? Something like:  

##### Update an object
```go
// Update multiple fields
// Only works for non-zero value fields
err := db.Update(&User{ID: 10, Name: "Jack", Age: 45})

// Update a single field
// Also works for zero-value fields (like bool, empty string, ...)
err := db.UpdateField(&User{ID: 10}, "Age", 0)
```

**Comment by skaldesh** [comment]
I created a [PR](https://github.com/asdine/storm/pull/279)

**Comment by asdine** [comment]
Thank you @skaldesh! Sorry I didn't see the notification on this issue
