### ISSUE TITLE
Support NextSequence

### ISSUE THREAD

**Issue by bep** [asdine/storm#3]
Nice project! 

It would be even nicer if one could define `ID uint64` and have it populated by the bucket´s `NextSequence` for new entities.

**Comment by asdine** [comment]
Great idea!
`Save` would set the ID only for the ID field that is a zero value and that is of `int64`,  `uint64`, `int` or `uint` types. What do you think?

**Comment by bep** [comment]
>  What do you think?

Makes sense.

**Comment by asdine** [comment]
Fixed by 160c0b08853eecb322a1c04254b7d0ef3d9ee18d
