### ISSUE TITLE
AutoIncrement doesn't set the ID field

### ISSUE THREAD

**Issue by Oregon-Tech-Ninja** [asdine/storm#30]
AutoIncrement doesn't set the ID field of the variable, which is making it absurdly difficult to update with the .Save() function. Couldn't we call AutoIncrement before marshaling the data and save that into the field so I don't end up with a bunch of |Key:124, Value{ID=0}| in the database?

**Comment by asdine** [comment]
Can you provide an example so i can reproduce the bug?

**Comment by Oregon-Tech-Ninja** [comment]
So take a bunch of inputs from the website form and shove em into a struct. If I'm editing a post, then there is an ID field which is hidden from the user, but gets sent to the program. If I'm creating a new post, then there is no ID field so auto increment can do its thing. Auto increment is working, but the ID field in the struct is left with 0 partially because the data seems to be marshaled before the ID is incremented. I proposed a really crappy code change last night before falling asleep I believe. Today I was going to test it out in my own code, but I thought this would be a common use case since go is largely used for web-services.

**Comment by Oregon-Tech-Ninja** [comment]
Also, there should be a good way to find by ID, it isn't clear in the readme, and one could just call Bolt and do it themselves, but people looking for this ORM would probably like having a simple function to call. But that's a lesser issue at this point in time.

**Comment by bep** [comment]
Have you enabled the AutoIncrement feature?

As to find with ID, db.One("ID", ...) should work.

**Comment by asdine** [comment]
I have found the bug; the data gets encoded before the autoIncrement part so it is saved without the right ID. The encode part was taken out of the transaction to avoid having long running transactions, but the `NextSequence`has to be in a transaction to work. I guess we need to move the encoding part inside the transaction if autoIncrement mode is enabled.

**Comment by whatisgravity** [comment]
Does the auto increment feature other fields besides ID? I wanted an index field and use a different field for an ID.
