### ISSUE TITLE
Batch support

### ISSUE THREAD

**Issue by asdine** [asdine/storm#31]
`Batch` writes can be very important when dealing with concurrency.
Passing an option to `Save` can be a good solution to activate the `Batch`instead of the `Update` for specific writes.
The option must be ignored if already in transaction though

**Comment by vansante** [comment]
Hi,

I am wondering what the priority on this issue is. It sounds like its just an extra param and a bit of logic, which is hopefully not too hard. Can this be implemented?

Thanks in advance!

**Comment by asdine** [comment]
@vansante It is scheduled for the next release of Storm. You can follow [this milestone](https://github.com/asdine/storm/milestones/0.5.0) to now more about the release
