### ISSUE TITLE
How to access the NextSequence in a Node.

### ISSUE THREAD

**Issue by nchampsavoir** [asdine/storm#34]
BoltDB provides a very useful NextSequence method on every bucket that returns an autoincrementing integer for the bucket. Since Storm does not provide direct access to the bucket (Its encapsulated in a Node), how does one access the NextSequence?

One way to do it would be to add a NextSequence method on the Node. Would you be open to that?

**Comment by bep** [comment]
>One way to do it would be to add a NextSequence method on the Node. Would you be open to that?

The `NextSequence` would only be relevant on `Node` when `Node` is in a write transaction. I agree it could be useful, but it could also be confusing if not well thought through.

So:

* If already in a write transaction, use that?
* If no transaction, create one?
* If in a read transaction? Panic?

**Comment by asdine** [comment]
If the reason you want to use `NextSequence` is to auto Increment your primary key, you can use the  `storm.AutoIncrement()` option.

If not, can you explain your use case?

**Comment by nchampsavoir** [comment]
@asdine Indeed it was. I just found out about AutoIncrement. I can't think of any other use cases so I'm closing the issue.
