### ISSUE TITLE
Simple Query Engine

### ISSUE THREAD

**Issue by asdine** [asdine/storm#43]
There should be a low level engine that executes the queries to BoltDB.
This engine would be able to fetch one or more values based on some options:

- greater than, greater than and equal
- less than, less than and equal
- in, not in
- skip, limit
- count only (also for special queries)
- etc.

This engine would also be used by indexes to fetch indexed values and could also be exported for those who want to make custom queries.

When possible, every call to BoltDB would be made via this engine.

Example with `One`:

- `db.One`
- `Index`
- Engine fetches the id from the index
- Engine fetches the data

This engine would be able to find records without indexes (see #42)

**Comment by bep** [comment]
I assume `or` and `and` is included in the above?

**Comment by asdine** [comment]
Yes it is

**Comment by asdine** [comment]
I have built an AST system that contains filters (the name node was already taken) that handles every options (except count), It is working pretty good.
I still need to figure out how the API will look like:

- DSL?
- query language?
- ...?

**Comment by bep** [comment]
I would prefer a DSL, but I guess it depends ... on the complexity of the queries ... Not sure if is possible to post some examples for discussion?

**Comment by asdine** [comment]
Sure, here are some:

```go
// Complex query
q := db.Query("(Age > 10 && Age < 21) or (Group in Admin,"Staff" and Status == verified)")

q := storm.Query().Gt("Age", 10).And().Lt("Age", 21).Or().In("Group", []string{"Admin", "Staff"}).And().Eq("Status", "Verified")

db.Fetch(q, &users)
```

**Comment by bep** [comment]
I will sleep on it ...

Some inspiration may be had in Hibernate's criteria builder ... At some point you will (maybe) have a concept of relations, so the query (or criteria ... or whatever) might as well know about the type(s) to query... Maybe ...

I will sleep on it. But this will be useful.

**Comment by bep** [comment]
I have slept.

I want something that:

1. Is easy to look at and understand (paris well with `gofmt`etc.)
2. Is composable (think dynamic construction)
3. Is flexible (makes it possible for end user to create operators etc.)

None of your examples fits the bill above. My take below assumes a future `join` syntax. I have no idea how that would play.

```go
q := storm.Select(&users, &roles).
		Where(
			And(
				Gt("Age", 10),
				Lt("Age", 21),
			),
			Or(
				In("Group", []string{"Admin", "Staff"}),
			),
			And(
				Eq("Status", "Verified"),
			)
	)

q.Execute()
```

Your example was hard to read, so I'm not even sure the above is "correct", and that kind of makes my point ...

**Comment by joeblew99** [comment]
What about using the DSL built into goa ?
This is a DSL for code generation.

Here is my idea about it that i posted:
https://github.com/goadesign/goa/issues/517

Would be great to get critical analysis on this...

**Comment by asdine** [comment]
@joeblew99 can you elaborate please?

@bep your example is indeed more correct, i like it.

Here is my revised version, please feel free to comment it:

```go
err := storm.Select(&users, storm.Gt("Age", 10))
```
Here we a have a `Select` function that takes a variadic filter/criteria argument. It fills `&users` and returns an error.

Now, let's say we have this query: `Age > 10 && Age < 21 && Status == "verified"`

```go
err = storm.Select(&users,
	storm.Gt("Age", 10),
	storm.And(
		storm.Ls("Age", 21),
	),
	storm.And(
		storm.Eq("Status", "Verified"),
	),
)
```
`storm.And` and `storm.Or` are also filters/criterias. Their primary use is to allow to chain criterias.
They take a variadic filter/criteria argument so it can also be used like this:

```go
err = storm.Select(&users,
	storm.And(
		storm.Gt("Age", 10),
		storm.Ls("Age", 21),
		storm.Eq("Status", "Verified"),	
	),
	storm.Or(
		storm.In("Group", []string{"Admin", "Staff"}),
	),
)
```

In the example above, storm.And takes multiple arguments. It allows to group criterias together for a "all or nothing" case. This example is like the following query: 
`(Age > 10 && Age < 21 && Status == "Verified") || Group in ("Admin", "Staff)"`

By default, we can also consider that chaining simple criterias is like using the `storm.And` function:

```go
err = storm.Select(&users,
	storm.Gt("Age", 10),
	storm.And(
		storm.Ls("Age", 21),
	),
	storm.And(
		storm.Eq("Status", "Verified"),
	),
)
```

is equivalent to this:

```go
err = storm.Select(&users,
	storm.Gt("Age", 10),
	storm.Ls("Age", 21),
	storm.Eq("Status", "Verified"),
)
```

This is only a first draft

**Comment by bep** [comment]
Much better.

I assume these can be chained deeper:

```go
err = storm.Select(&users,
    storm.And(
         storm.Or(
            storm.Gt("Age", 10),
            storm.Eq("Name"Eric),
       )
    ),
    storm.Or(
        storm.In("Group", []string{"Admin", "Staff"}),
    ),
)
```

And also `negated`:

```go
err = storm.Select(&users,
    storm.Not(
        storm.Gt("Age", 10),
        storm.Ls("Age", 21),
        storm.Eq("Status", "Verified"),
    )
)
```

**Comment by bep** [comment]
On an added note: I would put this in its own package.

**Comment by asdine** [comment]
Yes they can totally be chained deeper.
As for the package, what would you suggest?

**Comment by bep** [comment]
> As for the package, what would you suggest?

I would suggest keeping the `Select` on top level, then the filters etc. in `guery`.

**Comment by asdine** [comment]
> then the filters etc. in guery

typo?

**Comment by asdine** [comment]
I really don't know what name i should give this package 😄 , something short would be great.
Would a one letter package be correct?

We'd have:

```go

import "github.com/asdine/storm/q"

err = storm.Select(&users,
    q.Not(
        q.Gt("Age", 10),
        q.Ls("Age", 21),
        q.Eq("Status", "Verified"),
    )
)
```

**Comment by bep** [comment]
Yes, I agree about the one letter. I have a similar library, and I have used 2 or 3 char package names. It may look odd as a package, but it is a blessing once you start to use it.

**Comment by joeblew99** [comment]
hey a bit late to this party..
i like it, and the name "q".

Asdine, which part did not make sense in what i wrote ?

**Comment by asdine** [comment]
@joeblew99 How the goa DSL could be used for Storm?

**Comment by joeblew99** [comment]
goa is a 2 layer cake.
first layer is generates is the Service layer
second layer is the Data Access Layer (DAL). the payloads and media types declared in the Service layer as automatically converted to and from the DAL.
Explained here:
http://goa.design/extend/gorma/

The DSL at the DAL level is called Gorma.
Its pluggable though :) 
Gorma strongly adheres to the Active Record pattern (as per in link above), and so its an opportunity to generate the DAL to talk to BoltDB, and actually any other KV store.

I think what it depends upon, in terms of Level of Effort, is how easy it is to map the Active Record pattern to a KV store.  I think you would have a better understanding of that, but i noticed you are busy on the Query (q) layer a the moment, and so that query layer can be generated by goa is what i see.

I would be able to help on this. I have been using goa for a week and its really impressive, and under very good hands. Its also very easy to get the hang off. 

The reason i am interested in it is because for some projects a SQL DB fits the requirements, but often a KV store is a better fit. The reasons are a combination of factors as we all both know.

**Comment by bep** [comment]
@joeblew99 I'm afraid I don't understand it, either -- but it seems like a strange fit, or a hammer for a nail, for a simple library like Storm (which is pretty heavy on reflection; taking that out makes it a totally different library ...).

**Comment by asdine** [comment]
@joeblew99 what you're proposing seems more like some sort of "storma", a plugin for goa, and its complexity would depend on the storm DSL (q).

As bep said, Storm is a simple library, and it must remain focused on one goal. But nothing prevents anyone (in fact, i encourage it) to create repositories for adapters or plugins to other libraries to improve the usage of this library coupled with the work of other people.

As for reflection, Storm depends on it by choice, the same way as `json.Marshal` does

**Comment by joeblew99** [comment]
Agree with your point.

This is what happened with gorm and gorma

I can do the storma part, but it relies on storm offering an active record
pattern of sort. This is the crux of why I raised this.

**Comment by alexdeefuse** [comment]
Hi,

Any updates on this?

Thanks,
Alex

**Comment by asdine** [comment]
@alexdeefuse working on it 👍

**Comment by alexdeefuse** [comment]
Hi @asdine,

Thanks for your reply. The code you're working on, could you push this to a separate branch?
I'd be interested in getting involved to speed things along.

Best,
Alex

**Comment by asdine** [comment]
Hi @alexdeefuse,

I will this week end, it is still a draft of a draft for now
