### ISSUE TITLE
Provide an easy way to re-index existing data

### ISSUE THREAD

**Issue by bits01** [asdine/storm#49]
If adding a new index to an existing struct, any already persisted data would have to be re-indexed by re-saving each item again. It would be nice to have a simple way to do it without each user writing the same loop.

Ideally storm would detect it and just do it automatically, but for that it would probably need to persist some info about indexes on each struct.

**Comment by malaschitz** [comment]
Maybe in __storm_metadata store description of all index. For example: 
"user":"{ID:id,Email:unique,Age:index}"

When it is changed, than reindex all objects.

**Comment by asdine** [comment]
I think automatically reindexing data can add unnecessary overhead for the common user.
Changing indexes isn't something that happens a lot in my opinion, so adding a check at every request will be useless 99% of the time.
