### ISSUE TITLE
Do not mix value and pointer receivers

### ISSUE THREAD

**Issue by bits01** [asdine/storm#52]
See `transaction.go` line 4, `Begin()` takes a value receiver but all other methods take a pointer receiver.
https://github.com/asdine/storm/blob/master/transaction.go#L4
The reason is this:
http://dave.cheney.net/2015/11/18/wednesday-pop-quiz-spot-the-race

The solution is simple, once you have a pointer receiver, make all methods on a type pointer receivers.

Not sure whether there's some other code in storm that does the same thing, `Node.Begin()` is what I ran into so far.

**Comment by bep** [comment]
transaction.Begin and some others have value receiver for a reason; they return a new `*Node` copy.

**Comment by bits01** [comment]
Why does the Node need to be copied on Begin() It's a confusing usage model where the caller holds a *Node, begins a transaction then needs to use a different *Node to commit/rollback?

**Comment by bep** [comment]
Because the Node holds state that is local to a transaction and a given bucket.

**Comment by bep** [comment]
As to consusing: The alternative would be to make the copy inside the function, in this case it is crystal clear just by looking at the signature what is going on.

**Comment by bits01** [comment]
Not sure I understand the goroutine safety model around Node. Is it OK to hold on and use a *Node from multiple goroutines?

I'd like to have a root Node (bucket) where storm saves all its data as to not pollute the root level of boltdb. My application will manually manage transactions, rather than getting a txn per Save/One operation as there will be more than 1 operation per "request" and I would like a transactional view for both reading and saving multiple objects.
I thought I'd be able to do something like:
```
n := db.From("storm")
n.Begin(true/false)
// do some work
n.Commit() // or n.Rollback(), error handling aside
```
But it seems that instead the usage model in this case is:
```
n = n.Begin(true/false)
```
There's no use for the `*Node` returned from `db.From("storm")`

**Comment by bep** [comment]
>There's no use for the *Node returned from db.From("storm")

There is if you don't need "manual transaction" handling.

>Is it OK to hold on to and use a *Node from multiple goroutines?

Sure. But it will only be as safe as operations on the open Bolt connection.

**Comment by bep** [comment]
If you change `Begin` to a pointer receiver, then you will have data race bonanca!

**Comment by asdine** [comment]
`Node` is passed by value in `From` because the state created by `From` must be held by a `Node` copy. Think of `From` as a way to create your own scoped `storm.DB`.
```go
users := db.From('users')

users.Save(...)
...

// using a transaction
tx := users.Begin(true)
tx.Save(...)
tx.Commit()
...
```

`Begin` creates a `*bolt.Tx` that needs to be saved somewhere. It is saved in a `Node` copy (in the example above, that's the variable called `tx`) in a field called [`Node#Tx`](https://github.com/asdine/storm/blob/master/node.go#L13)
If we don't do that, `Node#tx` would be shared accross multiple goroutines and could possibly be modified by one of them -> race

**Comment by bits01** [comment]
I now understand the idea behind it. My impression was that Node behave just like DB, but that's not the case. Thank you for all the comments.
