### ISSUE TITLE
If bucket does not exist, Node.One() should return ErrNotFound

### ISSUE THREAD

**Issue by bits01** [asdine/storm#53]
If a bucket does not yet exist, `Node.One()` currently fails with:
`fmt.Errorf("bucket %s doesn't exist", info.Name)`

This happens if for example you try to look up an object by ID but no objects of that type have been saved yet. It is much more usable to simply return `ErrNotFound`. Alternatively, fail with an error that can be easily checked, rather than the generic `fmt.Errorf(...)`

**Comment by bits01** [comment]
Glad to see you agree and that it will be fixed. I'm currently checking the error msg on the error that I get back, which is far from ideal.

One suggestion if you want to return `ErrNotFound` but also indicate `ErrBucketDoesntExist`: you could make use of an error framework that provides causality (there are a few out there, or it's easy enough to create a custom error). Then you return `ErrNotFound` which would let you call `Cause()` on it which would return `ErrBucketDoesntExist` for those apps that really care why something was not found. But I suspect most apps just care that an item doesn't exist, the missing bucket is just an implementation detail.

**Comment by asdine** [comment]
I also don't think having `ErrBucketDoesntExist ` would be useful, It should be transparent and always return `ErrNotFound` when either the bucket doesn't exist or the resource is not found, just like MongoDB's collections.
I don't think `Cause` is necessary in this library (except if someone really thinks it is)

**Comment by bits01** [comment]
`ErrNotFound` should be just fine.

**Comment by asdine** [comment]
Interested in making a PR?

**Comment by bits01** [comment]
Of course.

**Comment by bits01** [comment]
PR #54 

(@asdine you love emojis :) )

**Comment by asdine** [comment]
(i love them 👯 )
