### ISSUE TITLE
Patch autoincrement to take a specified field?

### ISSUE THREAD

**Issue by whatisgravity** [asdine/storm#55]
I'd like to auto increment but not use that field as the index. Quick glance indicated it was not yet possible. Would you be interested in this change?

**Comment by asdine** [comment]
That would be great! A new struct tag would be nice to specify which field should be auto incremented (something like "auto-increment" or "increment" or "ai", any idea is welcome).

I think the `storm.AutoIncrement` option should still be required. The advantage of disabling the AutoIncrement is that the struct encoding takes place outside of the Bolt transaction.

**Comment by bep** [comment]
I would suggest simply naming the tag `increment`

**Comment by whatisgravity** [comment]
Sorry for not responding earlier, thanks for the suggestions, I will put it together soon as I have free time.
