### ISSUE TITLE
[Feature Request] Update function on existing structures

### ISSUE THREAD

**Issue by hardcoar** [asdine/storm#57]
I don't know how you implement an update on an existing structures guys, but i think we can all agree that an update function for an existing structure would be awesome.

For now, it's fetch, copy, delete in db, edit copied, save for me.

how do you guys do updates on existing structures?

**Comment by asdine** [comment]
You don't need to delete in db to update your structure.

```go

type User struct {
  ID int
  Name string
  Age int
}

db.Save(&User{
  ID: 1,
  Name: "John",
  Age: 10,
})

...

// now if you want to update the age field
// First fetch your user
var u User
db.One("ID", 1, &u)

// then update the field
u.Age = 20

// then save
db.Save(&u)
```

Of course, a function that would avoid fetching the object first would be great

**Comment by Comdex** [comment]
I think  a update function for one field in a structure will be great, now I must pass all info with a structure is not so good.

**Comment by asdine** [comment]
To update, we need:
- an instance of the type, so we can decode the record in it
- the bucket name
- the ID
- the fields to update
- the new values to set

So I was thinking about something like this:
```go
err := db.Update(&User{ID: 1, Age: 20})
```

Basically, you pass an object with the values that need to change (plus the ID).
The good side is that you can update several fields at a time.
The downside is that if you want to set a field to a zero value you can't.

So we can add another function
```go
err := db.UpdateField(&User{ID: 1}, "Age", 0)
```
You can only update one field
But you can set it to a zero value

@hardcoar @Comdex what do you guys think?

**Comment by Comdex** [comment]
@asdine  I think so
