### ISSUE TITLE
Drop func should take something other than a string

### ISSUE THREAD

**Issue by bep** [asdine/storm#58]
I started using the Drop func today, and the API felt a little weird.

```
func (n *Node) Save(data interface{}) error
```
```
func (n *Node) Drop(bucketName string) error
```
The first one creates a bucket if it doesn't exist. I don't really know what the bucket name is, and I need it if I want to drop it. I really don't care either. I guess the struct User will end up in the bucket "User", but now I have a loosely typed code, not very refactor-friendly.

**Comment by asdine** [comment]
Indeed, `Drop` should take a(n empty) struct instead of the bucketName.

**Comment by asdine** [comment]
The reason why i am using a string is to be able to drop buckets created by `From` and all their children:

```go
n := db.From("b1", "b2", "b3")
err := n.Save(&SimpleUser{ID: 10, Name: "John"})
assert.NoError(t, err)

err = db.From("b1").Drop("b2")
assert.NoError(t, err)
```

`Drop` should be able to take a string or a struct and remove accordingly
