### ISSUE TITLE
Add composite keys and indexes

### ISSUE THREAD

**Issue by bep** [asdine/storm#59]
Natural keys tend to be composites. Not sure how hard this is to implement, but it would be nice.

**Comment by asdine** [comment]
We already have composite indexes when using structs as indexes:
- [Struct example](https://github.com/asdine/storm/blob/master/structs_test.go#L37-L40)
- [Test](https://github.com/asdine/storm/blob/master/save_test.go#L106-L123)

But i guess it should be documented

**Comment by bep** [comment]
OK, how do I query that via `storm.One`?

**Comment by asdine** [comment]
For the test example we would do like this:

```go
err = db.One("InlineStruct", struct {
	A float32
	B float64
}{A: 10.0, B: 12.0}, &b)

```

**Comment by jypelle** [comment]
How to create an index for each part of the composite key ?

I tried:

```go
type ArtistSong struct {
	ArtistSongId struct {
		ArtistId string `storm:"index"`
		SongId   string `storm:"index"`
	} `storm:"id, inline"`
}
```

without success (storm doesn't recognize "id" + "inline" on the same tag)

**Comment by jypelle** [comment]
A workaround:
```go
type ArtistSong struct {
	ArtistSongId struct {
		ArtistId string
		SongId   string
	} `storm:"id"`
	ArtistId string `storm:"index"`
	SongId string `storm:"index"`
}
```

But you have redundancies...
