### ISSUE TITLE
Add "some interfaces"

### ISSUE THREAD

**Issue by bep** [asdine/storm#64]
See https://github.com/asdine/storm/blob/master/scan_test.go#L89

There are some natural interfaces inside Storm (node vs db etc.). I'm not sure what or who they are, but they can help simplify some code. If only to DRY up some tests. scan_test has 100% line coverage. If not for the interface I would probably have stopped around 80%.

**Comment by asdine** [comment]
Here is the first step 9423b4753d3. `Node` is now an interface and the implementation `node` is unexported. `DB` implements `Node` so you can now use either `*DB` or `Node`

**Comment by bep** [comment]
... that is a big interface ... but it is a start.

**Comment by asdine** [comment]
Yeah i thought the same, and it may grow bigger in the future, so it has to be broken into several small interfaces.
I think there are some easy parts, transaction functions can have their own interface, the query functions (from `Save` to `Select`)...
`Node` would be embedding all of those interfaces i think

**Comment by bep** [comment]
> Node would be embedding all of those interfaces i think

Yes, that would be the way to go.
