### ISSUE TITLE
Ascending and Descending

### ISSUE THREAD

**Issue by techjanitor** [asdine/storm#66]
With Bolt you can use a cursor and go from the end -> start/start -> end. Storm seems to always return everything in ascending order. Is there any way to reverse the order All() etc return their records in? This would make stuff like record paging super easy ;D

To clarify, I also mean changing the order while utilizing Limit() and Skip()

**Comment by asdine** [comment]
Fixed by ff2b8db and 60fc2dd. `Reverse` now works on indexes and all the query methods

**Comment by techjanitor** [comment]
Nice thx
