### ISSUE TITLE
LastInsertId() functionality for AutoIncrement()

### ISSUE THREAD

**Issue by techjanitor** [asdine/storm#67]
Just an idea, but when using AutoIncrement() it would be useful to have a function similar to LastInserId() in the sql package:

https://golang.org/pkg/database/sql/#Result

>         // LastInsertId returns the integer generated by the database
        // in response to a command. Typically this will be from an
        // "auto increment" column when inserting a new row. Not all
        // databases support this feature, and the syntax of such
        // statements varies.

In a transaction you can get the new ID and use it for other stuff. Right now it's not straight forward to get the id of an item that has been inserted. I assume this could be returned from Bolt's NextSequence() or similar?

**Comment by bep** [comment]
You don't need that. The ID field in your struct gets updated (with the value of NextSequence).

**Comment by techjanitor** [comment]
Wow nice, missed that! Thanks
