### ISSUE TITLE
Add support for nested buckets

### ISSUE THREAD

**Issue by bep** [asdine/storm#7]
BoltDB supports nested `buckets`, but it's not implemented in `Storm`. 

As to "why do we need this?":

Many database applications have natural partitions, where it is typically one partition in use at a time. 

With `GitHub` as an example: A user has many repositories, but looks mostly at a single repository at a time, with its:

* Code (Git repo)
* Issues
* Pull requests
* Settings
* ...

In the world of relational databases this is solved with `where clauses` and `joins`.

Translated to the `BoltDB` world we could:

1. Filter all your entities by some repositoryID, which gets messy, fast ... and how do we delete a repository?
2. Store all in one big object graph, which makes filtering easier, but doesn't scale.
3. Partition the application into `buckets`.

`Storm` currently stores everything below the root bucket with a bucket name derived from the struct name and package. This is perfectly fine for many applications.

**Suggestion: New bucket tag that points to the parent bucket:**

```go
type Issue struct {
	ParentBucket      [][]string `storm:"container"`
}
```
* This would work fine with `Save` operations.
* But would not work with `Find` and `One` etc.

This could be solved by either 

* Adding a variadic (optional) `parentBucket ...string` to these methods:

```go
func (s *DB)  Find(fieldName string, value interface{}, to interface{}, parentBucket ...string) error {
	//
}
```
* Adding a new concept of a container/bucket and a way to switch between them, so only the method receiver changes:

```go
func (c *Container)  Find(fieldName string, value interface{}, to interface{}) error {
	//
}
```

* ...?

Not sure what is best/simplest, but it should good enough as a foundation for discussion.

Some additional integration/helpers would be nice, but the above is a start.

**Comment by asdine** [comment]
Great idea @bep!
My only concern is about providing a simple API for that.

If i understand correctly, the idea is to be able to fetch an object with all of its related object in one go (like with a sql `join`) ?

Or to save / fetch an object to/from a nested bucket?

Either way this raises the question of how to handle relationships in Storm.

**Comment by bep** [comment]
>If i understand correctly, the idea is to be able to fetch an object with all of its related objects in one go (like with a sql join) ?

>Or to save / fetch an object to/from a nested bucket?

My primary motivation is to keep **unrelated** objects separated, but you are right that this is about relationships: These entities belong to project `A` so we put them in bucket `A`.  The "simple API is a challenge".

**Comment by asdine** [comment]
The problem is that i don't see on the API side a benefit for the user, beside knowing that related objects are in nested buckets.
Can you provide fake code that would illustrate this?

I think we need to think of relationships as a whole, because keeping unrelated things separated means in a way grouping related things together.

If we save children objects in nested buckets, it must be for something really interesting for the user, for example:

- To easily be able to declare relationships between objects, visually: _i have a `Repo`, a `Repo` has `Issue`s, `Code` ..._ (nesting objects together and using tags?)
- To query an object and all or some of its related/sub objects.
- To query a sub object directly
- ?

All the above points are just thoughts but i believe if we start to think of relationships that would be some interesting features

**Comment by bep** [comment]
>If we save children objects in nested buckets

I'm talking about a "bucket tree" that in the most common case is one level, not an object graph.

```
Repo (ID: 1)
-- Issues
  -- Comment
-- Code
Repo (ID: 2)
-- Issues
  -- Comment
-- Code
```

You may say that:

* An issue an is related to a repo and find a clever way to flatten/unflatten the object graph (because storing it as one big blob isn't realistic).

The above problem is hard to solve. I would be happy if you came up with a way to do that, but this gets easier for the head if you say the relation is very strong: *An issue is owned by the repository and there is next to none interaction between two repositories. They live their own life.*

* If I want to work on *Repo 1* I switch to *bucket 2*
* If I want to delete *Repo 1* I delete *bucket 2*
* If I want a similar repo, I copy *bucket 2* into *bucket 3* and start working with that.

I will think about better examples. If I realistically wants something like the above in `Storm` as of today, I would have to use several databases. Which could work, I guess.

**Comment by bep** [comment]
See #9 

The test case is pretty lame and the implementation isn't done -- but I hope it gets my point through. This is my idea in its simplest form. It will fill my current requirements, but it does require "some code" outside of Storm to keep track of the buckets ...

**Comment by asdine** [comment]
That's exactly what i was about to propose, i like it.

I believe we are in the right direction so we can now focus on making this work.

- Should we have some sort of absolute root (that would be `storm.DB`) and create nodes from it with the `DB.From()` method? Those nodes would also have a `From` method to be able to create other nodes.
The idea is to separate `DB` (the root) from the rest of the tree in case we add fields in the future that would only be useful in `DB` (for example `Path`), so the nodes will remain lightweight. If we do, what would be the name? `Node`, `Bucket`, ...?

- Should we prevent subs to close the database?

- `Init` should call `createBucketIfNotExists` too.

**Comment by bep** [comment]
I think Bolt's own design on this is a good reference:

* Eeach transaction have an unexported `root` Bucket that is delegated to for `CreateBucket` etc. 
* Since this is a BoltDB library and not a generic DB abstraction, I would call a bucket for ... bucket. 
* You could delegate to the root for all the `Find`, `Save` etc.... maybe, but it would probably be better to make it clear to the user that he/she works on a `Bucket` (even if it is the root; less work to maintain).
* So it's is either `DB.One`  or `DB.Root.One` 
* I guess `DB.From("a").From("b") => /a/b
* As to closing, I agree - but that will be solved if you create a `Bucket` (or `Node`) type.

**Comment by bep** [comment]
>I guess DB.From("a").From("b") => /a/b

To answer myself: No, that would be confusing, but we could add an `Append` func too, so:

```
DB.From("a").From("b") => b
DB.From("a").Append("b") => /a/b
```

**Comment by asdine** [comment]
`DB.From` will return a `storm.Bucket` so i think it feels more natural to have `DB.From("a").From("b")` => /a/b.
When you use `createBucket` from a bucket in BoltDB you create a nested bucket, it acts like a node

**Comment by bep** [comment]
>>would be the name? Node, Bucket, ...?

Rethinking: Having to package-prefix ´storm.Bucket` all the time would confuse, so I think `Node` would be a better fit.

As yo From:

```
db := ...
n1 := db.From("a").From("b") => /a/b/
n2 := db.From("c").From("d") => /c/d/
n1_2 := n1.From("c") => /a/b/c
...
```

Yes, that is intuitive.

**Comment by asdine** [comment]
`Node` would be more relevant you are right, as `Bucket` would make the user believe that we have our own version of a `bolt.Bucket`, it would be confusing.

**Comment by bep** [comment]
>Node would be more relevant you are right, 
Agree.
