### ISSUE TITLE
Return id after Save

### ISSUE THREAD

**Issue by WangFenjin** [asdine/storm#71]
Hi,

Could we return the AutoIncrementId after call save? Or could you point out how to get the id?

Thanks.

**Comment by asdine** [comment]
The id is automatically inserted in your ID field (or the field tag as id):

```go
// With AutoIncrement on

type User struct {
  ID int
  Name string
}

u := User{Name: "John"}
db.Save(&u)

fmt.Println(u.ID)
// 1
```

**Comment by asdine** [comment]
I am closing this issue, if you still have an issue with the ID please reopen

**Comment by WangFenjin** [comment]
Hi @asdine , sorry for late response, your solution is right.

Thanks.
