### ISSUE TITLE
buckets

### ISSUE THREAD

**Issue by spx** [asdine/storm#78]
hi,
is any way to set bucket for save? 
eg i want save &Users{} to users_china and users_russia

**Comment by asdine** [comment]
You can use nested buckets for that:

```go
users = []User{..., ..., ..., ...}
db.From("users_china").Save(&users)
db.From("users_russia").Save(&users)
```

**Comment by rskumar** [comment]
How bucket name is calculated in queries, when `.From(...)` is not specified? I couldn't find it in doc, how storm decides which bucket to choose for any operation?
