### ISSUE TITLE
sort

### ISSUE THREAD

**Issue by spx** [asdine/storm#79]
mhz, you wrote that indexed field is sorted but inresult i get unsorted
db.From("tv3").Select(q.Gte("Timestamp", 1472981431)).Find(&videos)
i get
15 {ID:25 Timestamp:1472982298 Channel:tv3 Filename:stream-1472982298.ts Dirname:2016/09/04/12 Duration:10}
16 {ID:26 Timestamp:1472982356 Channel:tv3 Filename:stream-1472982356.ts Dirname:2016/09/04/12 Duration:10}
17 {ID:27 Timestamp:1472982365 Channel:tv3 Filename:stream-1472982365.ts Dirname:2016/09/04/12 Duration:10}
18 {ID:9 Timestamp:1472981432 Channel:tv3 Filename:stream-1472981432.ts Dirname:2016/09/04/12 Duration:10}

**Comment by asdine** [comment]
I did not, the sort order is not guaranteed.
Also for this query you should definitely set an index on `Timestamp` and use `db.Range()`, it will be faster

```go
type YourType {
  ...
  Timestamp int `storm:"index"`
  ...
}

err := db.Range("Timestamp", 1472981431, time.Now().Unix(), &list)
```

If you want to sort the results you need to use the [sort](https://golang.org/pkg/sort/) package (at least for now)

**Comment by spx** [comment]
ok, thanks
