### ISSUE TITLE
No need to index the Primary Key

### ISSUE THREAD

**Issue by alessandrousseglioviretta** [asdine/storm#8]
An index for the Primary Key is redundant, it just adds a read op and some storage space, as the PKs are readily available in the top level bucket.

**Comment by asdine** [comment]
Definitely. The ID is currently treated as any other key and we can easily optimize it by removing the useless call.

**Comment by bep** [comment]
But it should be optimized in the `One` method and not adding another method to learn.

**Comment by asdine** [comment]
No it's all about optimization. If i remove the `UniqueIndex` on IDs on save, i will need to optimize `One` and`All`.
They both access the indexes before getting from the bucket.

**Comment by Depado** [comment]
Just commenting here even though it's a 4 years old issue because I can't seem to find the information elsewhere.
As of `v3.2.0` I still have the `__storm_index_ID` which maps the ID with itself, which is clearly redundant. Is there something special to do to remove said index?

**Comment by Depado** [comment]
It looks like this changed was reverted with 68fc73b635f890fe7ba2f3b15ce80c85b28a744f when the `id` tag was re-attributed an index. But maybe I'm out of touch with what's going on, I don't have the time to check all the commits and discussions regarding that. Is that index now required?
Changing `f.Index = tagUniqueIdx` to `f.Index = ""` removes the index associated with the ID. But I don't know if that will keep working as before.
