### ISSUE TITLE
write performance

### ISSUE THREAD

**Issue by spx** [asdine/storm#83]
hi,
is any way to speed up this?
https://play.golang.org/p/LYVmsy3ysD i need to insert 700 000 rows

Mindaugass-MacBook-Pro:epg_bolt mindaugas$ time go run main.go --config config.ini
parsing xml
storm begins
num: 0, time: 2.85197ms
num: 1000, time: 2.026768464s
num: 2000, time: 6.523655515s
num: 3000, time: 9.663367105s
num: 4000, time: 11.105321635s
num: 5000, time: 11.937392684s
num: 6000, time: 14.066639588s
num: 7000, time: 17.177086791s
num: 8000, time: 21.325859315s
num: 9000, time: 20.814317701s
num: 10000, time: 25.686991882s
num: 11000, time: 25.98401264s
num: 12000, time: 29.643677727s
num: 13000, time: 38.521215154s

**Comment by bep** [comment]
Start by moving

tx.From("epg").

Out of the loop

**Comment by spx** [comment]
better https://play.golang.org/p/xjUHWyyKk8 by still slow
Mindaugass-MacBook-Pro:epg_bolt mindaugas$ time go run main.go 
parsing xml
storm begins
num: 0, time: 1µs
num: 1000, time: 709.56425ms
num: 2000, time: 2.960213213s
num: 3000, time: 4.088162302s
num: 4000, time: 5.511388711s
num: 5000, time: 6.39532179s
num: 6000, time: 8.908257133s
num: 7000, time: 13.706947s
num: 8000, time: 11.613228077s
num: 9000, time: 11.649461918s
num: 10000, time: 11.889420703s
num: 11000, time: 18.842339374s
num: 12000, time: 18.009929456s

**Comment by bep** [comment]
You kind of lost my point. I may chime in later when not on mobile, but I suggest you take another look at your own code.

**Comment by bep** [comment]
You want to partition the saves into transactions, 1000 per save sounds right, but test it.

But what you don't want do to is to create 699999 you don't need.

So in your original code, replace this:

```go
tx.From("epg").Save(&item)
```

with:

```go
tx.Save(&item)
```

And move the "bucket selector" out of the loop:

```go
tx := db.From("epg")
tx, _ = tx.Begin(true)
```

Or something like that. You are sloppy with your error handling, and there is a one-off error in the transaction commit logic, but I guess that is outside the scope of this question.

**Comment by asdine** [comment]
@spx I am closing this since the problem comes from the implementation rather than from Storm itself. If you still encounters write performance and think we can improve Storm don't hesitate opening again please
