### ISSUE TITLE
Segfault on DB.Save()

### ISSUE THREAD

**Issue by AaronO** [asdine/storm#86]
#We use BoltDB as an index and metadata store for a file cache, used as part of GitBook's hosting system.

One of the `edge` nodes crashed with a `SEGFAULT` after a few million requests. I've attached stacktraces below.

It fails with a `SEGFAULT` in `Tx.Commit()` -> [Bucket.spill()](https://github.com/boltdb/bolt/blob/05e441d7b3ded9164c5b912521504e7711dd0ba2/bucket.go#L598) -> [Node.write()](https://github.com/boltdb/bolt/blob/05e441d7b3ded9164c5b912521504e7711dd0ba2/node.go#L205)

### Environment

* Go: `1.7rc2`
* BoltDB: `v1.2.1-5-g05e441d` - `05e441d7b3ded9164c5b912521504e7711dd0ba2`
* Storm: 97b157d5b760af7ddc878aca8b833de6fec335e8

### Screenshot

<img width="1185" alt="screen shot 2016-09-19 at 4 53 15 pm" src="https://cloud.githubusercontent.com/assets/949223/18636564/9964b700-7e89-11e6-9dcf-cbfaf33b29aa.png">

### Pretty stacktrace

```
1: running [Created by edge.(*Refresher).loop @ .:0]
    runtime    panic.go:566        throw(0xe94a1f, 0x5)
    runtime    sigpanic_unix.go:27 sigpanic()
    bolt       node.go:205         (*node).write(0xc427ed4c40, 0xc42c5ffff0)
    bolt       bucket.go:598       (*Bucket).write(0xc427c3a700, 0xc425f01101, 0xc428b43158, 0x80)
    bolt       bucket.go:506       (*Bucket).spill(0xc427c3a640, 0xc425f01000, 0xc428b433c8)
    bolt       bucket.go:508       (*Bucket).spill(0xc427c3a600, 0xc425f00f00, 0xc428b43638)
    bolt       bucket.go:508       (*Bucket).spill(0xc42a6dba58, 0x99a82de, 0x147ce80)
    bolt       tx.go:163           (*Tx).Commit(0xc42a6dba40, 0, 0)
    bolt       db.go:602           (*DB).Update(0xc4200de3c0, 0xc428b438e0, 0, 0)
    storm      save.go:51          (*Node).Save(0xc4201a3620, 0xcda920, #9, 0x1, #9)
    storm      save.go:113         (*DB).Save(#4, 0xcda920, #9, 0x3, #8)
    macrophage index.go:108        thunderbolt.Set(0x134e4e0, #4, #8, 0x71, 0, 0, 0x60f, #2, #2, 0, ...)
    macrophage macro.go:132        (*Macrophage).MetaSet(#3, #7, 0x1f, #10, 0x51, 0x60f, #2, #2, #6, 0x24, ...)
    cache      write.go:67         CacheWriter.WriteMeta(#7, 0x1f, #10, 0x51, 0x134d760, #3, 0xc42c5ffd80, 0x60f, #1, #1, ...)
    edge       refresher.go:109    (*Refresher).refresh(#5, #7, 0x1f, #10, 0x51, 0x60f, #1, #1, #6, 0x24, ...)
    edge       refresher.go:179    (*Refresher).loop.func1(0xc4205fafc0, 0xc4205fafd0, 0xc42840e880, 0x71, #5, 0xc420054320)
    runtime    asm_amd64.s:2086    goexit()
```

### Raw stacktrace

```
unexpected fault address 0xc42c600000
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc42c600000 pc=0x877d46]

goroutine 57198547 [running]:
runtime.throw(0xe94a1f, 0x5)
	/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc428b42d60 sp=0xc428b42d40
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:27 +0x288 fp=0xc428b42db8 sp=0xc428b42d60
github.com/GitbookIO/cdn/vendor/github.com/boltdb/bolt.(*node).write(0xc427ed4c40, 0xc42c5ffff0)
	/go/src/github.com/GitbookIO/cdn/vendor/github.com/boltdb/bolt/node.go:205 +0x86 fp=0xc428b42ef8 sp=0xc428b42db8
github.com/GitbookIO/cdn/vendor/github.com/boltdb/bolt.(*Bucket).write(0xc427c3a700, 0xc425f01101, 0xc428b43158, 0x80)
	/go/src/github.com/GitbookIO/cdn/vendor/github.com/boltdb/bolt/bucket.go:598 +0xb1 fp=0xc428b42f58 sp=0xc428b42ef8
github.com/GitbookIO/cdn/vendor/github.com/boltdb/bolt.(*Bucket).spill(0xc427c3a640, 0xc425f01000, 0xc428b433c8)
	/go/src/github.com/GitbookIO/cdn/vendor/github.com/boltdb/bolt/bucket.go:506 +0x101 fp=0xc428b431c8 sp=0xc428b42f58
github.com/GitbookIO/cdn/vendor/github.com/boltdb/bolt.(*Bucket).spill(0xc427c3a600, 0xc425f00f00, 0xc428b43638)
	/go/src/github.com/GitbookIO/cdn/vendor/github.com/boltdb/bolt/bucket.go:508 +0x937 fp=0xc428b43438 sp=0xc428b431c8
github.com/GitbookIO/cdn/vendor/github.com/boltdb/bolt.(*Bucket).spill(0xc42a6dba58, 0x99a82de, 0x147ce80)
	/go/src/github.com/GitbookIO/cdn/vendor/github.com/boltdb/bolt/bucket.go:508 +0x937 fp=0xc428b436a8 sp=0xc428b43438
github.com/GitbookIO/cdn/vendor/github.com/boltdb/bolt.(*Tx).Commit(0xc42a6dba40, 0x0, 0x0)
	/go/src/github.com/GitbookIO/cdn/vendor/github.com/boltdb/bolt/tx.go:163 +0x125 fp=0xc428b437f8 sp=0xc428b436a8
github.com/GitbookIO/cdn/vendor/github.com/boltdb/bolt.(*DB).Update(0xc4200de3c0, 0xc428b438e0, 0x0, 0x0)
	/go/src/github.com/GitbookIO/cdn/vendor/github.com/boltdb/bolt/db.go:602 +0x10d fp=0xc428b43848 sp=0xc428b437f8
github.com/GitbookIO/cdn/vendor/github.com/asdine/storm.(*Node).Save(0xc4201a3620, 0xcda920, 0xc42a17a190, 0x1, 0xc42a17a190)
	/go/src/github.com/GitbookIO/cdn/vendor/github.com/asdine/storm/save.go:51 +0x271 fp=0xc428b43938 sp=0xc428b43848
github.com/GitbookIO/cdn/vendor/github.com/asdine/storm.(*DB).Save(0xc420375560, 0xcda920, 0xc42a17a190, 0x3, 0xc428a4aa00)
	/go/src/github.com/GitbookIO/cdn/vendor/github.com/asdine/storm/save.go:113 +0x43 fp=0xc428b43970 sp=0xc428b43938
github.com/GitbookIO/cdn/cache/macrophage.thunderbolt.Set(0x134e4e0, 0xc420375560, 0xc428a4aa00, 0x71, 0x0, 0x0, 0x60f, 0x57defcd8, 0x57defcd8, 0x0, ...)
	/go/src/github.com/GitbookIO/cdn/cache/macrophage/index.go:108 +0xaf fp=0xc428b439b0 sp=0xc428b43970
github.com/GitbookIO/cdn/cache/macrophage.(*Macrophage).MetaSet(0xc4201a4940, 0xc42805d820, 0x1f, 0xc42a53f9e0, 0x51, 0x60f, 0x57defcd8, 0x57defcd8, 0xc42558b440, 0x24, ...)
	/go/src/github.com/GitbookIO/cdn/cache/macrophage/macro.go:132 +0x15b fp=0xc428b43a80 sp=0xc428b439b0
github.com/GitbookIO/cdn/cache.CacheWriter.WriteMeta(0xc42805d820, 0x1f, 0xc42a53f9e0, 0x51, 0x134d760, 0xc4201a4940, 0xc42c5ffd80, 0x60f, 0x57def749, 0x57def749, ...)
	/go/src/github.com/GitbookIO/cdn/cache/write.go:67 +0x17c fp=0xc428b43b20 sp=0xc428b43a80
github.com/GitbookIO/cdn/edge.(*Refresher).refresh(0xc4203815c0, 0xc42805d820, 0x1f, 0xc42a53f9e0, 0x51, 0x60f, 0x57def749, 0x57def749, 0xc42558b440, 0x24, ...)
	/go/src/github.com/GitbookIO/cdn/edge/refresher.go:109 +0x7ff fp=0xc428b43ec0 sp=0xc428b43b20
github.com/GitbookIO/cdn/edge.(*Refresher).loop.func1(0xc4205fafc0, 0xc4205fafd0, 0xc42840e880, 0x71, 0xc4203815c0, 0xc420054320)
	/go/src/github.com/GitbookIO/cdn/edge/refresher.go:179 +0x12d fp=0xc428b43f70 sp=0xc428b43ec0
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc428b43f78 sp=0xc428b43f70
created by github.com/GitbookIO/cdn/edge.(*Refresher).loop
	/go/src/github.com/GitbookIO/cdn/edge/refresher.go:182 +0x2dd
```

**Comment by AaronO** [comment]
@asdine I don't think this is a high level bug, the nodes have processed tens of millions of requests, only one edge node crashed once with a `SEGFAULT`, so overall it's reliable, pretty much all requests hit the `boltdb` index, with at least a `read`, `write` volume is slightly lower.

Maybe this is the issue we're encountering: https://github.com/golang/go/issues/16772, which was fixed by https://github.com/boltdb/bolt/commit/92410e067395f10c8c93fad62c3e6c4b7aca82f0, released in `boltdb` @ `1.3.0`.

I'll try upgrading to `boltdb` @ `1.3.0`, leave it running and monitor for any crashes

**Comment by asdine** [comment]
@AaronO Yes i think it comes from that. Also you are using a version of `Storm` that's behind of HEAD by about a 100 commits, you should definitely upgrade to benefit from the various improvements

**Comment by AaronO** [comment]
More than happy to upgrade, `storm` is pretty cool 👍 (btw, I'm also ex botify/ulule, [many years back]).

What are the improvements ? Any breaking changes ?

Unfortunately not many people use [semver](http://semver.org/) in the Go community, any chance you could have tagged semver releases ? (We use it religiously, and it's great to pin dependencies in production)

**Comment by asdine** [comment]
Amazing you're also an ex Botify/Ulule guy! I'm glad you like `Storm` 👍 

There is only one big breaking change, the default `Codec` used : We moved from `gob` to `json`, essentially becauses it is sooo much faster with `Storm`. But if you are already using a database that uses `gob` you just need to pass the following option when opening a database:
```
db, _ := storm.Open(......., storm.Codec(gob.Codec))
```

A 100 commits is a lot, so i suggest doing some tests before running on production, if you experience any issue don't hesitate creating an issue.

As for SemVer, i think i definitely should use it for Storm 👍

**Comment by AaronO** [comment]
@asdine Yep, storm provides a nice abstraction with decent performance on top of `boltdb`. Our performance across millions of requests has been really good.

### Indexes 

Our CPU usage was very high when using many indexes (i only use 2 now), might want to put a warning in the `README.md` about that, though it should also be common knowledge for DB users that indexes can have a net negative performance impact on write heavy loads.

### GOB vs JSON

How big is the performance improvement of `gob` vs `json` ? (it might be worth clearing our index for that upgrade)

### Semver

Semver would be awesome, once you get used to it becomes automatic and has great advantages. In `go` we either put the version in a `VERSION` or `version.go` if it's a library and in the CLI's code if it's primarily a CLI. Then bump the version with a `Bump version to a.b.c` commit which only changes the version and is `git tag`'d as `a.b.c`.

### Semver commit log screenshot

<img width="803" alt="screen shot 2016-09-19 at 6 55 45 pm" src="https://cloud.githubusercontent.com/assets/949223/18640995/f71fba6e-7e9a-11e6-9f3f-f2dbdbda76ed.png">

You can also see that on one of our public go codebase's here: https://github.com/GitbookIO/micro-analytics/commits/master

**Comment by asdine** [comment]
@AaronO It is very nice to know that, thank you for your feedback.

If you need more performance and don't care about recreating a database (or migrate it) you should definitely use the Protocol Buffer Codec. All you need to do is to declare your structures in a proto file, compile it to go and activate the [protobuf](https://github.com/asdine/storm#provided-codecs) Codec for `Storm`. There is an example [here](https://github.com/asdine/storm/blob/master/codec/protobuf/simple_user.proto).
The difference can be huge

The difference between Gob and JSON has been discussed [here](https://github.com/asdine/storm/issues/72#issuecomment-242727817). The performance improvement is huge on reads (not on writes though)

Thanks for the Semver tip, i will definitely take a look at it :)

**Comment by AaronO** [comment]
@asdine Thanks for the `protobuf` pointer, maybe `json` and `ffjson` is good enough performance wise, though I guess `protobuf` would have a smaller memory footprint which would be cool.
Right now we still get decent performance with `gob`, I should probably write benchmarks before changing it.

Gonna close this issue, since it's really a `boltdb` issue and should be fixed for the meantime.

Thanks for your help and the pointers !
