### ISSUE TITLE
Marshal/Encode vs Unmarshal/Decode

### ISSUE THREAD

**Issue by bep** [asdine/storm#87]
We currently have:

```
type EncodeDecoder interface {
	Encode(v interface{}) ([]byte, error)
	Decode(b []byte, v interface{}) error
}
```

Which in the different implementations delegates to Marshal/Unmarshal or Encode/Decode (gob).

Go's stdlib have a distinction between `Marsha` (convert to `[]byte`) and `Encode` (stream to an `io.Writer`).

It is all put below the package `encoding` so i think Storm´s `Codec` is a good name for it. The interface, however, could maybe be renamed to:

```
type Marshaler interface {
	Marshal(v interface{}) ([]byte, error)
	Unmarshal(b []byte, v interface{}) error
}
```

This isn't really of world-class importance, but would maybe make the API a little bit more familiar to the common Gopher.

**Comment by asdine** [comment]
In the stdlib `Marshaler` is used to Marshal only. Shouldn't we simply rename the type `Codec` instead?

**Comment by bep** [comment]
We don't have a `Codec` type, we have a `codec` package and some `Codec` variables, and I think those fits OK.

I don't think the stdlib has a `Marshaler` interface, there is a ´BinaryMarshaler` and a `TextMarshaler` I think.

In our case it should maybe be `MarshalerUnmarshaler`, which is possibly fine ... I just borrowed from the `Spring Framework`, which has a `Marshaler` interface that does both. Not sure.

**Comment by bep** [comment]
>MarshalerUnmarshaler is more correct i think but... it's long!

I think `MarshalUnmarshaler` is even more correct ... and shorter.

So it would be ...

```go
type  MarshalUnmarshaler interface {
    Marshal(v interface{}) ([]byte, error)
    Unmarshal(b []byte, v interface{}) error
}
```
Lets sleep on it ... :-)

**Comment by asdine** [comment]
I slept on it and i think you're right, `MarshalUnmarshaler` is clear and lets the possibility to later have an `EncodeDecoder`that would handle streams
