### ISSUE TITLE
Using SemVer

### ISSUE THREAD

**Issue by asdine** [asdine/storm#88]
I have some ideas that will potentially break some things so i think i should start using SemVer to avoid causing a mess on other people's work.
I don't know at what version to start though. I don't think Storm is near v1 since there are still a few things to add to make it good enough (orderBy, expiration, map support, etc.)

**Comment by bep** [comment]
Not sure how you're gonna implement this, but it would be nice to also have some kind of versioning support as metadata in the database too. 

So, say a move from 0.5 to 0.6 would give an error about incompatibility, but 0.5 to 0.5.1 would be fine. This could also maybe trigger some automatic db migrations.

**Comment by asdine** [comment]
Great idea, i could start by storing the version in a `metadata` bucket.
Then check if the metadata bucket exists when using `Open`, check the version and return an error if is incompatible.

Do you think we should make automatic migrations? I would start by creating a `Migrate` method that would have to be triggered manually so the user would be able to make a backup of its db

**Comment by bep** [comment]
>Do you think we should make automatic migrations?

I haven´t though that through, the most important part is the "safety". I don't think it should be automatic, but it would be really useful if I could:

1. Call `Migrate("my.db")`
2. And Storm could evaluate if it had a migration path from the two version, including taking a backup of the original. 

It wouldn't have to be fancy, but should make, i.e., the JSON sorting change less painful for the end users.

**Comment by asdine** [comment]
Handling migrations raise several issues that need to be addressed first:

- What codec is used in this Node / Bucket?
- Has it been written with `Save` or with `Set` ? (the behaviour is different)
- Is this bucket managed by Storm or did the user use Bolt directly ?

If we know those informations, we would be able to Unmarshal the right values and replay them with the new code.

The first solution that comes to my mind is to store metadata in each bucket when it is created or when the first `Save` or `Set` is called against it.
With this solution we could also prevent this kind of mistakes (that wouldn't happen very often) by reading the metadata:

```go
db.Save(&User{......}) // json.Codec
n := db.WIthCodec(gob.Codec)
n.Save(&User{......}) //gob.Codec
```

**Comment by bep** [comment]
>The first solution that comes to my mind is to store metadata in each bucket when it is created or when the first Save or Set is called against it.

I don't think there are any other good options. But this would be really valuable. Even I have to think a little before doing `go get` on my Storm apps (I'm not so good at vendoring my personal apps).

**Comment by asdine** [comment]
Another problem arise: To rewrite records, they need to be unmarshalled to the concrete types used to marshal them. The `json` codec doesn't mind behing umarshalled to whatever variable, but `gob`, `protobuf`, and potentially any other codec, are more stricts...

For the user, migrating the database would mean migrating manually every node unfortunately.
Also, this way we may don't need to save the metadata in the bucket to know the codec, since the migration can't be done automatically.

Something like: 

```go
m, err := storm.NewMigrator("my.db")

// For the buckets that used Save
m.AddBucket(new(User), json.Codec)
m.AddBucket(new(Score), gob.Codec)

// For the buckets that used Set
m.AddKV("bucket name", new(int), new(string), json.Codec)

// Nested buckets
m.From("a", "b", "c").AddBucket(new(d), protobuf.Codec)

// Running by specifying a path. 
// Possibly we can make sure this path doesn't exist before running, to avoid any mistake
err = m.Run("new.db")
```

**Comment by bep** [comment]
>m.AddBucket(new(User), json.Codec)

Isnt´t here a way to serialize that info into the `metadata` field?

It does make it simpler from the Storm side, but ...

**Comment by asdine** [comment]
I don't know how actually. I didn't find any way to create an instance of a type by only specifying a string

```go
v := reflect.NewValueFromString("users.User") // awesome and scary
```

There is another solution: Scanning the code of the user and generate a migration file. But that would be hard i guess

**Comment by bep** [comment]
Yes, a user-defined migration would be the way to go. 

If you make a `migrator.Option` option type, where the first will be the orignal codec, and make that a vararg on both `Add*` and `Run`, then you could remove some boilterplate, and even make room for an `AddBuckets`:

```go
m.AddBuckets(new(User), new(Score))
m.Run("new.db", migrate.Options(json))
```

Or whatever.

**Comment by bep** [comment]
Or, thinking again: If you store the codec/struct pairs in metadata, you should be able to do:

```go
m.AddBuckets(new(User), new(Score))
```

And do the lookup of the codec based on the given type.

**Comment by asdine** [comment]
This is harder than expected.
I can't reuse functions from the Storm codebase in the `Migrator` because if they change they will break older migration tools.
Copying parts of functions gets messy and hard to maintain very quickly.
The migration tool must use some kind of freeze of the codebase it migrates to.
The other problem is that i often need unexported functions (i.e. `extract`), but if the migrator is in another package, things must be moved.

One solution that i have thought about is to create a separate repo for a migration tool that would contain a snapshot of each version of Storm in a sub directory (`v0.5/` for example) plus a `storm.Migrator` type inside.

The migrator would be able to call any function of Storm knowing that they're freezed + all the unexported types and funcs.

**Comment by bep** [comment]
Lets take the hardest problem first:

If you as part of your semversiong scheme also do version of your import paths, you can in your migrator package (in its own repo or just in a package, not much difference for the end user; importing it means Go-getting it):

```
import (
 "stormv1" github.com/asdine/storm/v1
 "stormv2" github.com/asdine/storm/v2
)
```

And then do a chain of needed migrations to get to the current version.

And if you put the `Migrator` type in the `storm` package (it should only have one method), you would solve many function issues.

**Comment by asdine** [comment]
I have created a [repo](https://github.com/asdine/storm-migrator) without the versioning of the import paths.
It is not fully tested and it only works with buckets created with `Save` for now. But if seems to work fine

**Comment by bep** [comment]
I was thinking more in the line of using

http://labix.org/gopkg.in

**Comment by asdine** [comment]
The thing is gopkg.in only works with >= v1.x
I would like to keep Storm under v1 for a while, until we have more things to propose. 
Also, the idea is once we get to v1, to ensure backward compatibility with v1.x and don't break things (or work on v2)

That's why i don't see any other solution at the moment.
The storm-migrator will live only until v1 i think

**Comment by bep** [comment]
OK, I didn't know that about gopkg.in.

**Comment by asdine** [comment]
The migrator is pretty much ready, it lacks documentation but it works. I will do more tests next week

**Comment by asdine** [comment]
The migrator is ready
